getAlby/hub

frontend/src/screens/wallet/Send.tsx
Fixes https://github.com/getAlby/hub/issues/18
=> fix: add proper handling of invoice

api/api.go, api/models.go, frontend/src/hooks/useTransactions.ts, frontend/src/screens/wallet/OnboardingChecklist.tsx, http/http_service.go, lnclient/lnd/lnd.go, wails/wails_handlers.go
- Adds support for `limit` and `offset` parameters
- Also adds the transaction hint in the Onboardsing Checklist
=> feat: support limit and offset in list transactions

lnclient/ldk/ldk.go
I think we need better monitoring of core parts of our system. If syncs fail we need to quickly be notified and check our electrs service, or reach out to users who may be unable to sync for whatever other reason and provide as much help as we can.
=> feat: fire events on failed sync

frontend/src/components/layouts/AppLayout.tsx, version/version.go
"Unknown version" doesn't really help much, so we can hide it.
=> fix: hide unknown version

frontend/package.json, frontend/src/components/TransactionItem.tsx, frontend/src/components/TransactionsList.tsx, frontend/src/components/ui/credenza.tsx, frontend/src/components/ui/drawer.tsx, frontend/src/hooks/useMediaQuery.ts, frontend/yarn.lock, lnclient/lnd/lnd.go
Uses [Credenza](https://github.com/redpangilinan/credenza)
=> feat: add transaction popup

frontend/src/components/MnemonicInputs.tsx, frontend/src/components/TransactionsList.tsx, frontend/src/components/connections/AppCard.tsx, frontend/src/screens/apps/AppCreated.tsx, frontend/src/screens/apps/AppList.tsx, frontend/src/screens/channels/Channels.tsx, frontend/src/screens/wallet/Send.tsx, frontend/src/screens/wallet/index.tsx
=> chore: descriptive class names and mark sensitive content

lnclient/breez/breez.go, lnclient/greenlight/greenlight.go, lnclient/ldk/ldk.go, lnclient/lnd/lnd.go
as per the nip-47 spec, pay_keysend TLV values are hex-encoded
Fixes https://github.com/getAlby/hub/issues/230
=> fix: correctly pass TLVs in NIP-47 pay_keysend

frontend/src/components/ui/theme-provider.tsx
Partly fixes #221
Older hubs had "dark" saved as the ui theme which now was rename to a explicit darkmode setting, however there is no theme named "dark". Thus the theme appears broken if you upgrade an older version of the hub, for new installs it should be fine.
=> fix: validate theme from storage

frontend/src/screens/channels/Channels.tsx, frontend/src/screens/channels/CurrentChannelOrder.tsx, frontend/src/screens/channels/IncreaseOutgoingCapacity.tsx
Fixes https://github.com/getAlby/hub/issues/236
- re-add primary open channel button
- add links to increase receiving capacity from outgoing and channel order pages so the user can always find it
=> feat: improve open channel ux flows

frontend/src/screens/Intro.tsx
Fixes https://github.com/getAlby/hub/issues/221
=> fix: force dark mode in intro

frontend/src/screens/channels/Channels.tsx, frontend/src/types.ts, lnclient/ldk/ldk.go, lnclient/models.go
=> fix: LDK mark channel as inactive and show error if counterparty forwarding info missing

frontend/src/components/TransactionItem.tsx
=> chore: remove unnecessary dark classes

api/api.go, cmd/http/main.go, main_wails.go, service/models.go, service/service.go, service/start.go, service/stop.go
Fixes https://github.com/getAlby/hub/issues/57
- Relay is now correctly shut down
- LNClient is stopped by waiting for the app context to be cancelled instead of manually
TESTS:
This does not cover the case if sigterm happens when the app is starting up (when the LNClient is being created), which could break the node as it will not be shutdown safely. I will create a separate issue for this one.
=> fix: stop nostr when app is shutdown and use context to stop lnclient

db/db.go, db/migrations/202407151352_autoincrement.go, db/migrations/migrate.go, frontend/src/screens/apps/AppCreated.tsx
Fixes https://github.com/getAlby/hub/issues/252
This PR adds autoincrement to the primary keys of all our tables which fixes weird bugs caused by ID reuse which is the default in SQLITE (if you delete app ID 7, then the next app you create will have ID 7 again). Only apps, app_permissions and user_configs are preserved. The other tables are dropped (payments are dropped as part of dynamic budgets, request_events and response_events are not critical)
TESTS:
=> fix: migrate existing tables to have autoincrementing primary keys

frontend/src/components/layouts/AppLayout.tsx
Fixes #253
Should I return `Outlet` instead of nothing? Didn't right now as it would be weird if the Sidebar pops up after a second everywhere, and info should be present for the Hub in any case.
https://github.com/user-attachments/assets/ae65cb3d-e1f4-4196-921d-7323dc3bbe64
=> chore: return if info is not loaded in app layout

lnclient/lnd/lnd.go
It is wrongly mentioned that -60000 sats are incoming although there are no channels waiting to be closed, and also this happens because total balance is less than the spendable balance (hence the -ve sign) which can never be the case
This happens because we remove the ReservedBalance from the TotalBalance in LND which makes TotalBalance less than ConfirmedBalance
From LDK docs
> **total_onchain_balance_sats:** [u64](https://doc.rust-lang.org/nightly/std/primitive.u64.html)
The total balance of our on-chain wallet.
**spendable_onchain_balance_sats:** [u64](https://doc.rust-lang.org/nightly/std/primitive.u64.html)
The currently spendable balance of our on-chain wallet.
This includes any sufficiently confirmed funds, minus [total_anchor_channels_reserve_sats](https://docs.rs/ldk-node/latest/ …
=> fix: spendable balance in lnd

frontend/src/components/TransactionItem.tsx, frontend/src/components/ui/credenza.tsx
=> fix: use credenza provider

lnclient/phoenixd/phoenixd.go, scripts/linux-x86_64/phoenixd/render.yaml
This makes finding the matching phoneixd in cloud environments easier. we default to http if that is not privided
=> Render.com phoneixd

lnclient/lnd/lnd.go
=> fix(lnd): total and spendable balance

api/transactions.go, db/migrations/202407201604_transactions_indexes.go, db/migrations/migrate.go, db/models.go, db/queries/get_budget_usage.go, db/queries/get_isolated_balance.go, lnclient/cashu/cashu.go, lnclient/ldk/ldk.go, lnclient/lnd/lnd.go, lnclient/models.go, lnclient/phoenixd/phoenixd.go, nip47/controllers/list_transactions_controller_test.go, nip47/controllers/lookup_invoice_controller_test.go, nip47/controllers/models.go, nip47/models/transactions.go, nip47/notifications/nip47_notifier_test.go, transactions/keysend_test.go, transactions/list_transactions_test.go, transactions/lookup_transaction_test.go, transactions/notifications_test.go, transactions/payments_test.go, transactions/transactions_service.go
Part of https://github.com/getAlby/hub/issues/299
=> chore: add transaction indexes, make fees non-nullable

api/api.go
App card (and app page) will show usage even if no budget is set.
=> fix: always calculate budget usage

frontend/src/hooks/useOnboardingData.ts, frontend/src/screens/wallet/OnboardingChecklist.tsx
Fixes #309 
- We now have numbers for those items, therefore i removed to sorting by the `checked` status (feels strange to have numbered items appear in the wrong order)
- Hide the onboarding checklist if all of the items have been completed
=> fix: checklist items

frontend/src/screens/channels/Channels.tsx
Fixes #283
Should I rename the Savings Balance to Onchain Balance?
=> chore: add tooltips for node balances

.env.example, alby/alby_oauth_service.go, alby/models.go, config/models.go, frontend/src/components/AuthCodeForm.tsx, http/alby_http_service.go, wails/wails_handlers.go
Fixes https://github.com/getAlby/hub/issues/298
=> feat: auto link alby account

frontend/src/screens/channels/IncreaseOutgoingCapacity.tsx
Fixes #282
Done similar to extension:
=> feat: show onchain balance in increase spending capacity screen

frontend/src/components/layouts/TwoColumnFullScreenLayout.tsx
=> feat: add back button in setup screen

frontend/src/screens/channels/first/FirstChannel.tsx
Fixes https://github.com/getAlby/hub/pull/343#pullrequestreview-2201488697
Now will show the migrate funds copy if the user has more than the minimum to migrate (100 sats)
=> fix: open first channel button copy

frontend/src/components/ui/button.tsx, frontend/src/screens/channels/IncreaseIncomingCapacity.tsx, frontend/src/screens/channels/IncreaseOutgoingCapacity.tsx, frontend/src/screens/channels/first/FirstChannel.tsx
Button tags in forms submit the form.
This means clicking the "Buy Bitcoin" link did not open the link but actually submit the form. According to the HTML spec a button tag must also not be nested into a hyperlink.
This PR removes those links from the form and uses hyperlinks with button styles (instead of a button tag)
note: I have no idea about those react elements/buttons
=> fix: button usage for links

frontend/src/components/TransactionItem.tsx
what value does it give? then all the entries say lightning invoice and it can only be a lightning invoice
=> chore: no default invoice memo

alby/alby_oauth_service.go, alby/models.go, frontend/src/components/AuthCodeForm.tsx, frontend/src/components/layouts/SettingsLayout.tsx, frontend/src/routes.tsx, frontend/src/screens/alby/AlbyAuthRedirect.tsx, frontend/src/screens/settings/AlbyAccount.tsx, http/alby_http_service.go, wails/wails_handlers.go
Fixes https://github.com/getAlby/hub/issues/289
Adds a new settings page http://localhost:5173/#/settings/alby-account
This currently does not remote the Alby Oauth account's NWC connection. I don't think this should necessarily be the same action
The first link is a bit wrong because it always goes to your currently logged in account on getalby.com which might not be the one logged in in the hub. It would be cool if we can pass something to getalby.com to detect that?
=> feat: unlink alby account

go.mod, go.sum
- only request fee estimates once, not per confirmation target
- fix incorrect argument name in send_to_address bindings
See https://github.com/getAlby/ldk-node/pull/40
=> fix: update LDK dependency with bugfixes

alby/alby_oauth_service.go, api/transactions.go, constants/constants.go, nip47/controllers/make_invoice_controller.go, nip47/controllers/make_invoice_controller_test.go, transactions/make_invoice_test.go, transactions/transactions_service.go
This enables apps to easily attach metadata to invoices rather than requiring an external database. This can currently be done by encoding data in the description field which will be included in the invoice itself, but there are a few downsides:
- it makes the invoice QR code harder to scan
- user doesn't understand the encoded content which should actually be a description
- description is limited to 639 bytes and then gets switched to a description hash, which can break apps
TODOs:
=> feat: add metadata field to make_invoice command

frontend/src/hooks/useAlbyBalance.ts, frontend/src/hooks/useAlbyMe.ts
fixes https://github.com/getAlby/hub/issues/373
Tested by navigating pages and checking XHR requests in my browser. Other calls deduplicate by default every 2 seconds - which we could review and possibly increase for some other calls too. However, this might be less important.
=> Fix: cache alby user calls

lnclient/ldk/ldk.go
With this we can have custom emails and monitors/workflows if a user opens a public and private channel for example
=> chore: include whether the channel is public or not in channel ready event

lnclient/lnd/lnd.go
This solves people with private channels having issues with invoice creation
=> fix: use private channels in invoice routing

.env.example, config/models.go, events/events.go, service/start.go
Desktop app was not logging events, which makes it hard to debug and see what is going on when users are having issues
=> chore: log events by default

lnclient/lnd/lnd.go
Fixes #394
Checks if the peer is already connected, and returns nil
=> fix: check if peer is already connected

lnclient/lnd/lnd.go
Fixes #388
We should also add a screen to display when the node is offline, which can be used by backends other than LDK, because currently Alby Hub goes blank if the node is offline with no message. But we can open a separate issue for that(?)
=> chore: stop subscription goroutines if node is stopped

frontend/package.json, frontend/src/components/CloseChannelDialog.tsx, frontend/src/components/channels/ChannelDropdownMenu.tsx, frontend/src/components/channels/ChannelsCards.tsx, frontend/src/components/channels/ChannelsTable.tsx, frontend/src/components/ui/radio-group.tsx, frontend/src/screens/channels/Channels.tsx, frontend/yarn.lock
`window.alert`, `prompt` and `confirm` don't work in wails. We can use [Dialog](https://wails.io/docs/reference/runtime/dialog/) but it has some limitations in [MacOS](https://stackoverflow.com/questions/26898941/ios-wkwebview-not-showing-javascript-alert-dialog). Also the flow for closing a channel involves the user to type "force close" which is not ideal. This PR replaces those with AlertDialog from shadcn for Wails support as well as design consistency
=> feat: add close channel dialog

api/api.go, api/models.go, frontend/src/screens/channels/IncreaseOutgoingCapacity.tsx, frontend/src/types.ts, lnclient/ldk/ldk.go, lnclient/lnd/lnd.go, lnclient/models.go
Fixes https://github.com/getAlby/hub/issues/416
=> fix: do not allow creating another outgoing channel while one has 0 confirmations

frontend/src/App.tsx, frontend/src/components/layouts/AppLayout.tsx
This should fix the loading issue when node is unlocked/not running
=> fix: do not show sidebar while loading

README.md, api/api.go, api/models.go, config/models.go, frontend/src/screens/Intro.tsx, frontend/src/screens/Welcome.tsx, frontend/src/types.ts
Closes https://github.com/getAlby/hub/issues/409
=> feat: add env variable for disabling advanced setup

go.mod, go.sum
See https://github.com/getAlby/ldk-node/pull/43
=> chore: bump ldk-node-go version

api/api.go, config/config.go, nip47/notifications/nip47_notifier.go, nip47/permissions/permissions.go, transactions/transactions_service.go
Related to https://github.com/getAlby/hub/issues/422
Closes https://github.com/getAlby/hub/issues/414
Improves query performance. From gorm:
> Using Find without a limit for single object db.Find(&user) will query the full table and return only the first object which is not performant and nondeterministic
=> fix: use take instead of find for single record lookups

api/api.go, config/config.go, nip47/permissions/permissions.go, transactions/transactions_service.go
Fixes some issues with https://github.com/getAlby/hub/pull/423
Take throws an error if a record is not found. With limit(1) and find, we can control what to do if the record does not exist.
=> fix: use limit and find rather than take

frontend/index.html, frontend/vite.config.ts, http/http_service.go
CSP is moved to the header which is more secure (e.g. Alby Hub can no longer be loaded in an iframe).
In development, we use the vite server, so a dev CSP is injected in this case. We need to keep them in sync to ensure you don't fix something in development, only to realize it's still broken in production.
=> feat: add secure middleware, move CSP to header

frontend/src/screens/apps/ShowApp.tsx, transactions/receive_keysend_test.go, transactions/transactions_service.go
Fixes https://github.com/getAlby/hub/issues/437
This loads the app for a keysend transaction from the custom key/value data.
it is using the app ID as costum value - the nostr key of the connection is a bit more private than the app id of the hub
=> feat: process podcasting custom key/value records

frontend/src/components/layouts/AppLayout.tsx
The navbar currently has some in-between breakpoints which makes it a little bit narrower. I don't think it's worth to maintain them as the differences are negligible but cause some problems: (e.g. with the version number here)
=> fix: remove navbar breakpoints

frontend/src/components/layouts/AppLayout.tsx
Links to Alby Cloud for users who don't have an Alby Cloud hub deployment
=> feat: add alby cloud link

api/backup.go, db/db.go, frontend/src/screens/BackupNodeSuccess.tsx, http/http_service.go, service/service.go
Fixes https://github.com/getAlby/hub/issues/472
We weren't shutting down the DB correctly which didn't save the full write-ahead log to the DB. This was causing issues when importing - it was using the old -shm and -wal files which were causing the imported nwc.db to be discarded.
- ensure full wal checkpoint is executed on shutdown
- correctly shutdown DB on normal exit
- shutdown service before exiting on backup restore
- remove JWT middleware from backup endpoint
- delete old nwc db files before backup restore to ensure restored files are used
Tests:
=> fix: migrate node

go.mod, go.sum, lnclient/ldk/ldk.go
Possibly fixes https://github.com/getAlby/hub/issues/478
- update ldk-node-go dependency (decreased esplora timeout, use separate esplora clients)
- do not do unnecessary fee estimates sync before full sync
- only update fee estimates every 5 minutes instead of once per minute
=> fix: attempt to fix LDK deadlock on bump transaction on double-spent utxo

.env.example, config/models.go, fly.toml
DEBUG can cause a lot of spam messages and the log files to get too large.
=> fix: ldk use info log level by default

api/api.go, api/models.go, frontend/src/screens/apps/NewApp.tsx, frontend/src/screens/apps/ShowApp.tsx, frontend/src/types.ts
Fixes #451
~⚠️ Needs design input on frontend (currently can break in small screens (<350px) and also doesn't have cancel option)~ Proceeding with this for now
<p>
</p>
<p>
</p>
=> feat: edit name in show app screen

frontend/src/components/CloseChannelDialogContent.tsx, frontend/src/components/MempoolAlert.tsx, frontend/src/screens/channels/IncreaseIncomingCapacity.tsx, frontend/src/screens/channels/IncreaseOutgoingCapacity.tsx, frontend/src/screens/channels/first/FirstChannel.tsx, frontend/src/screens/onchain/BuyBitcoin.tsx, frontend/src/screens/onchain/DepositBitcoin.tsx
Fixes https://github.com/getAlby/hub/issues/533
Adds this warning on all pages that require an onchain transaction
=> feat: add mempool fee alerts

api/api.go, config/config.go, config/models.go, frontend/src/screens/setup/SetupFinish.tsx, lnclient/cashu/cashu.go, service/start.go
Fixes https://github.com/getAlby/hub/issues/396
When running 1.6.0 the first time, the SetupCompleted check will rely on the user having an `AlbyUserIdentifier` or an existent LDK directory. This is not perfect, but I think the chance both are not set is very slim - and if a user does encounter this, we can give them instructions on how to do a db edit to set their user ID.
- finish can now be run again if node has never successfully started
- fix: use mutex for both setup and start endpoints
- fix: reduce setup finish timeout to 30 seconds from 3 minutes
- fix: cashu start does not handle invalid mints
=> feat: better error handling on setup

frontend/src/screens/setup/SetupPassword.tsx
Clicking on "I understand this password cannot be recovered" toggles the above checkbox which feels buggy
=> chore: secure password label id

scripts/linux-x86_64/phoenixd/README.md
Add command to make the install script executable in the instructions.
=> doc: Correct phoenixd install script instructions in readme

frontend/src/routes.tsx, frontend/src/screens/channels/auto/AutoChannel.tsx, frontend/src/screens/channels/auto/OpenedAutoChannel.tsx, frontend/src/screens/channels/auto/OpeningAutoChannel.tsx, frontend/src/screens/setup/SetupPassword.tsx
Closes https://github.com/getAlby/hub/issues/540
This flow is not linked from the UI. This is a way channels could possibly be offered for free after a force closure event. It is mostly a copy of the first channel flow, but without the alby funds migration logic and the copy has been updated to fit with any number of channels. Instead of checking for the existence of a channel, it'll check for a new channel and monitor that one. The entry point is `/channels/auto`.
=> feat: add new auto channel flow that works with existing channels

frontend/package.json
switching branches often can cause vite cache to get corrupted
=> chore: add force flag in dev mode

frontend/src/screens/wallet/index.tsx
fixes https://github.com/getAlby/hub/issues/561 by replacing the unhelpful low spending balance alert.
=> feat: show channel reserves alert on wallet page

cmd/http/main.go
We noticed logs of the echo server still handling requests after shutting down. Not sure why, but this is good to add anyway.
=> chore: add error handling for echo shutdown

frontend/src/screens/channels/Channels.tsx, frontend/src/types.ts, lnclient/ldk/ldk.go, lnclient/models.go
Fixes https://github.com/getAlby/hub/issues/601
Only LDK is supported for now.
The LDK API is not so easy to deal with here so a lot of code to gather all the different balances, but it's isolated in one place.
=> feat: show pending balances from channel closures (LDK)

api/api.go, service/stop.go
Fixes https://github.com/getAlby/hub/issues/391
=> fix: do not allow lnclient access while it is shutting down

frontend/src/components/CloseChannelDialogContent.tsx, lnclient/lnd/lnd.go
=> feat: show pending balance from channel closures in lnd

lnclient/phoenixd/phoenixd.go
otherwise the invoice amount is shown as 0
=> fix: phoenix: return amount on make invoice call

frontend/src/screens/apps/ShowApp.tsx
Fixing https://feedback.getalby.com/-alby-hub-request-a-feature/posts/message-when-deleting-isolated-connection
> When deleting an isolated connection I think it would be good if there was a message advising what happens to the sats that are associated with that connection.
> I think it could be easy to get the fear that sats may be lost. Perhaps a line advising people that no funds will be removed and will still be available from the main wallet could be added to the message in the included screenshot.
**Screenshot**
=> fix: improve delete connection confirmation dialog copy

api/api.go
Isolated apps should not have anything shared from the main account. The isolated connection would also not see any transaction from that lud16.
=> fix: remove lud16 from isolated app secrets

alby/alby_oauth_service.go, api/lsp.go
Fixes https://github.com/getAlby/hub/issues/634
I unfortunately cannot test this currently on Mutinynet
=> fix: use 1 channel confirmation for non-LDK node types

frontend/src/components/AppAvatar.tsx, frontend/src/components/SidebarHint.tsx, frontend/src/components/TransactionItem.tsx, frontend/src/components/connections/AppCard.tsx, frontend/src/components/layouts/AppLayout.tsx, frontend/src/components/ui/alert-dialog.tsx, frontend/src/components/ui/dialog.tsx, frontend/src/components/ui/input.tsx, frontend/src/screens/Home.tsx, frontend/src/screens/channels/Channels.tsx
Fixes quite some UI issues in mobile. See screenshots for Before vs After:
<table>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
<table>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
<table>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
<table>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
<table>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
<table>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
<table>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
=> feat: mobile UI fixes

scripts/linux-x86_64/install.sh
Albyhub service had a config error after re-running the Linux installation script [here](https://github.com/getAlby/hub/tree/master/scripts/linux-x86_64#alby-hub-on-a-linux-server) caused by the albyhub.service written twice.
=> Removes any existing albyhub.service to prevent duplicating

frontend/src/screens/wallet/index.tsx
if the user needs some channels we link to the flow to open the first
channel. Otherwise we directly link to transfer the Alby funds.
=> fix: correct link to migrate funds

config/config.go
With this change we always take the configuration from the user configuration in the DB and not overwrite it with the env variables.
So in case a user already has a config or imports an existing DB the environment variables will be ignored.
This has the downside that that once started env variables can not be updated/changed. But this also means that a DB import can be made on setups where env variables are pre configured.
=> chore: precedence for user config from the DB

frontend/src/screens/wallet/Send.tsx, frontend/src/screens/wallet/send/LnurlPay.tsx
fixes https://github.com/getAlby/hub/issues/650
@im-adithya how it was implemented before was very unstable. We should avoid editing internals and instead use the public API of the object.
=> fix: lnurl pay to use existing lightning address

README.md
This simplifies the top of the README and adds links for users to quickly get started. Development docs are moved further down.
=> doc: simplify README

lnclient/breez/breez.go, lnclient/cashu/cashu.go, lnclient/greenlight/greenlight.go, lnclient/ldk/ldk.go, lnclient/lnd/lnd.go, lnclient/models.go, lnclient/phoenixd/phoenixd.go, nip47/controllers/get_balance_controller.go, tests/mock_ln_client.go
Fixes #669
This removes the repeated `GetBalance` method which is redundant due to `GetBalances` and uses the latter in NIP47 Get Balance Handler
=> chore: remove get balance method from LN client

.env.example, api/models.go, api/transactions.go, config/models.go, db/db.go, frontend/src/components/AppAvatar.tsx, frontend/src/components/TransactionItem.tsx, frontend/src/components/layouts/SendLayout.tsx, frontend/src/types.ts, nip47/controllers/list_transactions_controller.go, nip47/controllers/list_transactions_controller_test.go, service/service.go, tests/test_service.go, transactions/list_transactions_test.go, transactions/transactions_service.go
Fixes https://github.com/getAlby/hub/issues/426
Failed and unsettled outgoing transactions are now shown in the transaction list. Pending transactions have a pulse animation.
I also added an alert on the send page if the user has any pending payments, to avoid the chance they accidentally try pay again.
Note: Listing transactions is now ordered by `updated_at` rather than `settled_at, created_at`
TODOs:
=> feat: show pending and failed outgoing transactions

frontend/src/components/SuggestedAppData.tsx, frontend/src/components/ui/button.tsx, frontend/src/routes.tsx, frontend/src/screens/Home.tsx, frontend/src/screens/internal-apps/AlbyGo.tsx
Would actually be quite easy to create a dynamic page with some fallback (for the "how to connect" section) that does the same thing for all available apps. Not sure if we should take this other step right away, wdyt?
=> feat: alby go app

alby/alby_oauth_service.go, alby/models.go, frontend/src/screens/channels/IncreaseIncomingCapacity.tsx, frontend/src/screens/channels/IncreaseOutgoingCapacity.tsx, frontend/src/types.ts
Fixes https://github.com/getAlby/hub/issues/677
The checkbox is disabled, with a message when you hover over it. I think this might be sufficient for now.
=> feat: disable public channel checkbox for channel partners that do not support public channels

scripts/linux-x86_64/Caddyfile.example, scripts/linux-x86_64/README.md, scripts/linux-x86_64/install.sh
Fixes https://github.com/getAlby/hub/issues/681
This only applies to the Linux x86_64 service and introduces inconsistencies between ports.
=> fix: use a less-used port for the alby hub service so it doesn't conflict with other running apps

lnclient/ldk/ldk.go
Fixes https://github.com/getAlby/hub/issues/683
=> fix: use short sync interval while LDK channel is waiting to become active

lnclient/ldk/ldk.go, lnclient/lnd/lnd.go
Fixes #644
We recently saw an issue where people saw balance differently in Umbrel, Hub and the Extension
For example:
`1 748 499` - Umbrel
`1 747 569` - Extension
`  987 439` - Hub Node page
This PR makes the Hub Node page return the same balance as the extension. The difference of 930 between Umbrel and Extension is not solved by this PR as it is because of an unsettled HTLC (again, I suspect that it is an invoice of value 500 sats but this additional 430 sats is cut from the balance and I don't know why that is the case)
=> fix: use channel balance api in get balances (LND)

alby/alby_oauth_service.go, events/models.go, frontend/src/components/layouts/SettingsLayout.tsx, frontend/src/hooks/useOnboardingData.ts, frontend/src/routes.tsx, frontend/src/screens/BackupMnemonic.tsx, go.mod, go.sum, lnclient/ldk/ldk.go, lnclient/ldk/ldk_event_broadcaster.go, service/start.go
=> feat: include LDK channel monitors in static channel backups

frontend/src/components/TransferFundsButton.tsx, frontend/src/screens/channels/Channels.tsx, frontend/src/screens/wallet/index.tsx
Fixes #692
Also reloading channels so the liquidity changes in Node screen
=> fix: reload balances, txs and channels after transfer is complete

frontend/src/components/TransactionItem.tsx
<table>
<tr>
<td>
<h3>Before</h3>
</td>
<td>
<h3>After</h3>
</td>
</tr>
<td>
</td>
<td>
</td>
</tr>
</table>
=> chore: hide preimage in failed payment dialog

frontend/package.json, frontend/src/components/layouts/AppLayout.tsx, frontend/yarn.lock
The current Hub won't show 1.10.1 as the new update in the Sidebar because we do a `"1.9.0" >= "1.10.1"` comparsion which results in `true` meaning the current version is wrongly shown as up to date. This fixes the comparision logic by adding the `compareVersions` utils function.
=> fix: version comparision logic

constants/constants.go, transactions/make_invoice_test.go
Some invoices seem to include quite a lot of metadata. So much, it actually runs into the INVOICE_METADATA_MAX_LENGTH limit. 
We need to find out what metadata clients embed here and why, but in the meantime let's increase the limit to prevent failed payments.
=> fix: increase metadata limit

frontend/src/components/Scopes.tsx
Adds `get_info` permission to isolated apps, previously created isolated app connections will remain unchanged
=> fix: add get_info to isolated app permissions

frontend/src/screens/apps/AppCreated.tsx
New name across NWC apps is "Connection Secret", but since this is obvious on the connect screen anyway I just removed it completely.
=> fix: remove obsolete mention of pairing secret

.github/workflows/create-release.yaml, .github/workflows/wails.yml, build/darwin/gon-notarize.json, wails.json, wails/wails_app.go
Changes the title from `albyhub` in wails app to `Alby Hub`
Also fixes #466
=> chore: use proper title in wails

frontend/src/components/BudgetAmountSelect.tsx, frontend/src/components/connections/AlbyConnectionCard.tsx
fixes https://github.com/getAlby/hub/issues/721
=> fix: require 21k+ sats budget for alby connection card

frontend/src/screens/BackupMnemonic.tsx, frontend/src/screens/setup/ImportMnemonic.tsx, frontend/src/screens/setup/SetupPassword.tsx
Fixes https://github.com/getAlby/hub/issues/645
Adds a link to our guide, makes copy on the backup and seed imports more clear and warns against importing from seed if you have open channels
=> feat: clearer backup and restore info

frontend/src/screens/channels/Channels.tsx, lnclient/ldk/ldk.go, lnclient/lnd/lnd.go, lnclient/models.go
Fixes https://github.com/getAlby/hub/issues/752
Fixes https://github.com/getAlby/hub/issues/612
There is overlap in balance from pending closed channels and total onchain balance.
They will show as incoming in the total onchain balance once the channel becomes sweepable. Therefore, this PR no longer manually includes balances from pending closed channels in the "incoming" amount on the savings balance card.
This PR also adds extra balance info that can be retrieved from debug tools -> get balances which is useful for debugging channels that are stuck (e.g. unconfirmed) or to know if the funds on a channel are still locked, and which counterparty the channel is with.
=> fix: do not show duplicated incoming funds from channel closures

alby/alby_oauth_service.go, api/api.go, api/models.go, api/transactions.go, apps/apps_service.go, db/models.go, frontend/src/components/IsolatedAppTopupDialog.tsx, frontend/src/screens/apps/AppCreated.tsx, frontend/src/screens/apps/ShowApp.tsx, frontend/src/screens/internal-apps/UncleJim.tsx, http/http_service.go, nip47/controllers/make_invoice_controller.go, transactions/transactions_service.go, wails/wails_app.go, wails/wails_handlers.go
Closes https://github.com/getAlby/hub/issues/479
Adds ability to "Increase" the balance of an isolated app in 3 places (new isolated app connection, isolated app connection page, friends & family app)
Also renames the db service as this only had app-related functionality, and cleaned up some previous TODOs there.
On the UI it's just called "Increase". The user is warned that they must actually have enough real balance on their channels to make payments, as the isolated app balance could be larger than their channel balance.
TODO:
=> feat: increase isolated app balance

frontend/src/screens/Start.tsx
startups can take some time. It should be faster but I think it is worse when a user submits the startup again.
=> chore: extend startup timeout

alby/alby_oauth_service.go, frontend/src/screens/channels/Channels.tsx, frontend/src/screens/channels/first/FirstChannel.tsx, frontend/src/screens/channels/first/OpenedFirstChannel.tsx, frontend/src/screens/wallet/index.tsx
Fixes https://github.com/getAlby/hub/issues/781
- renamed "migrate" to "transfer" to match getalby.com/node page 
- when transferring funds on first channel open, will not repeatedly drain funds (except when user only has small amount of funds left over)
- transfer funds endpoint now caps the amount to transfer to 1M sats.
=> fix: limit funds transferred from shared wallet to hub node

frontend/src/screens/internal-apps/BuzzPay.tsx
Fixes https://github.com/getAlby/hub/issues/759
`name` param is not read correctly and needs fixing on the PoS side.
=> fix: use buzzpay new URL format

alby/alby_oauth_service.go
Fixes https://github.com/getAlby/hub/issues/765
=> fix: change failed to refresh existing token log from error to warn level

alby/alby_oauth_service.go
fixes https://github.com/getAlby/hub/issues/769
This happens when node_id is included in both the channels backup event and the event publisher global properties.
I have updated the log to debug as the node_id must be part of the event properties. In this case, I think the log just does not need to be error level, as the event properties always take precedence over the global properties.
=> fix: change key already exists error to debug log

service/start.go
The eos check is not needed because:
- The request events are ephemeral
- When we update the relay to keep undelivered ephemeral events, only undelivered events will be consumed 
Fixes https://github.com/getAlby/hub/issues/743
=> fix: remove eos check after connecting to relay

api/api.go, api/models.go, frontend/src/components/Permissions.tsx, frontend/src/components/Scopes.tsx, frontend/src/screens/apps/ShowApp.tsx, frontend/src/types.ts
Closes https://github.com/getAlby/hub/issues/783
Closes https://github.com/getAlby/hub/issues/598
- allows creating an isolated app with custom permissions
- allows editing isolated app permissions
- allows changing the isolated flag on an existing app (with a confirmation dialog if it is isolated -> not isolated)
- moves isolated app backend type support check to backend
=> feat: improve isolated app support

README.md, apps/apps_service.go, service/create_app_consumer.go, service/delete_app_consumer.go, service/start.go, tests/create_app.go, transactions/transactions_service.go
Fixes https://github.com/getAlby/hub/issues/319
Also renames app events which did not have the `nwc_` prefix (all other events have it)
=> feat: add budget warning event, rename app events

lnclient/ldk/ldk.go
(if the user force closes from their side this will show as pending funds from closed channels until the timelock ends)
=> fix: re-add pending balance for LightningBalanceClaimableAwaitingConfirmations

frontend/src/components/layouts/AppLayout.tsx, frontend/src/hooks/useNotifyReceivedPayments.ts, frontend/src/screens/wallet/receive/ReceiveInvoice.tsx
Followup of https://github.com/getAlby/hub/pull/815 that will show a notification if you receive payments via lightning address.
I am not sure it's really needed though, or should just go on the receive page so that the rest of the app does not necessarily poll to get the latest transaction
=> feat: app-wide received payment notifications

frontend/src/components/TransactionItem.tsx, frontend/src/types.ts
Fixes https://github.com/getAlby/hub/issues/577
Alternative to https://github.com/getAlby/hub/pull/678
Shows LUD-18 and NIP-57 data for received payments in the transaction list.
This iteration only shows text data. Nostr zap profile name and picture would require a separate service or deeper nostr integration which might not be worthwhile right now.
=> feat: show transaction metadata in transaction list

frontend/src/screens/ConnectAlbyAccount.tsx
Fixes https://github.com/getAlby/hub/issues/782
A temporary addition without a major redesign.
=> feat: add encrypted backups card to connect alby account page

frontend/src/components/AppHeader.tsx, frontend/src/routes.tsx, frontend/src/screens/BackupMnemonic.tsx, frontend/src/screens/channels/Channels.tsx, frontend/src/screens/channels/CurrentChannelOrder.tsx, frontend/src/screens/channels/IncreaseIncomingCapacity.tsx, frontend/src/screens/channels/IncreaseOutgoingCapacity.tsx, frontend/src/screens/onchain/BuyBitcoin.tsx, frontend/src/screens/onchain/DepositBitcoin.tsx, frontend/src/screens/setup/ImportMnemonic.tsx, frontend/src/screens/wallet/WithdrawOnchainFunds.tsx
Partially addresses https://github.com/getAlby/hub/issues/675
- remove extra buttons from node page
- change default channel flow to increase receiving capacity
- update copy on node page and manual open channel flows
- add tooltips on new channel amounts
=> feat: simplify node page and manual open channel flows

frontend/package.json, frontend/yarn.lock
This fixes an issue where crypto subtle cannot be used in non-https environments.
We still need to completely remove bitcoin connect to remove the older version of lightning tools.
=> chore: update lightning tools dependency

frontend/src/screens/wallet/index.tsx
For some reason I missed this value is in sats, not millisats.
=> fix: unmet fee reserve check on wallet page

alby/alby_oauth_service.go
Unfortunately I didn't catch this in dev mode since I disabled automatic linking.
We cannot link at this point because the LNClient is not started, therefore cannot get the supported methods to create the app.
=> fix: disable auto link alby account

frontend/src/screens/setup/node/LNDForm.tsx, lnclient/lnd/lnd.go, lnclient/lnd/wrapper/lnd.go
Fixes #405
EDIT: We decided that it's good to always verify if a certificate is passed by the user. If users raise concerns about using their own self-signed certificate (as it fails the verification), we'll think of adding a checkbox saying "I'm using a self signed certificate" which when checked can skip the cert verification process.
As we anyways ask the user to provide the certificate, it doesn't make any sense to verify the server certificate and host name, the same is also true for the case when the TLS certificate is not provided (as the user agrees to the risk it poses). So this adds `InsecureSkipVerify: true` in both cases while generating transport credentials.
(And yes, this PR also adds the possibility to continue without adding a TLS certificate)
<table>
<tr>
<td><img …
=> fix: allow self-signed certificates and to skip during setup

api/api.go, api/models.go, frontend/src/hooks/useLinkAccount.ts, frontend/src/hooks/useMigrateLDKStorage.ts, frontend/src/screens/settings/AlbyAccount.tsx, frontend/src/types.ts, go.mod, go.sum, http/http_service.go, lnclient/ldk/ldk.go, wails/wails_handlers.go
Closes https://github.com/getAlby/hub/issues/864
Requires https://github.com/getAlby/ldk-node/pull/57
TODO:
```
svc.cfg.SetUpdate("LdkVssEnabled", "true", "")
svc.cfg.SetUpdate("LdkMigrateStorage", "VSS", "")
```
=> feat: migrate to VSS

lnclient/lnd/lnd.go, lnclient/lnd/wrapper/lnd.go
Fixes #806
Adds a channel event susbcription to listen to channel closures.
`closureReason` can be the following:
- `"COOPERATIVE_CLOSE"`
- `"LOCAL_FORCE_CLOSE"`
- `"BREACH_CLOSE"`
- `"REMOTE_FORCE_CLOSE"`
- `"FUNDING_CANCELED"`
- `"ABANDONED"`
=> feat: fire channel open and closure events in lnd

frontend/src/components/connections/AlbyConnectionCard.tsx, frontend/src/components/connections/AppCardConnectionInfo.tsx
Fixes https://github.com/getAlby/hub/issues/474
- improve budget copy
- add tooltip that explains budget
- update alby account settings link when account is linked (goes to hub alby account settings page)
=> feat: improve Alby Account connection card

alby/alby_oauth_service.go, api/api.go, api/models.go, frontend/src/screens/settings/AlbyAccount.tsx, frontend/src/types.ts
e.g. we do not want a user to try to migrate if they actually cannot.
=> fix: only show vss info in alby account settings if vss is supported

transactions/isolated_app_payments_test.go
already tests in the same file for sufficient/insufficient budget based on the fee reserve, but not the fee reserve calculation function. I am just paranoid :grin:
=> chore: add tests for calculateFeeReserve

wails/wails_app.go
=> feat: show confirm exit dialog before closing desktop app

service/start.go
it seems users sometimes bypass the auth page, and therefore the alby account token is not valid before the node starts
related to https://github.com/getAlby/hub/issues/772
=> fix: check alby auth token is valid on start if alby account is connected

api/models.go, db/queries/get_isolated_balance.go, db/queries/get_isolated_balance_test.go, lnclient/ldk/ldk.go, lnclient/lnd/lnd.go, nip47/controllers/get_balance_controller.go, nip47/controllers/get_balance_controller_test.go, transactions/isolated_app_payments_test.go, transactions/keysend_test.go, transactions/self_payments_test.go, transactions/transactions_service.go
There are two isolated app (subwallet) vulnerabilities fixed in this PR:
- use signed integers in isolated app balance calculation to prevent integer overflow
- enforce fee limits when making payments
TESTING:
11 sats:
```
2025-01-05 08:33:37 TRACE [lightning::routing::router:3230] Ignored 0 candidate hops due to insufficient value contribution, 0 due to path length limit, 0 due to CLTV delta limit, 0 due to previous payment failure, 0 due to htlc_minimum_msat limit, 0 to avoid overpaying, 2 due to maximum total fee limit. Total: 2 ignored candidates.
2025-01-05 08:33:37 ERROR [lightning::ln::outbound_payment:997] Failed to find route for payment with id 8a5ecf53b069559f9c6e318a64fc2984d2f0931101170e60f581e7a1161521e6 and hash 8a5ecf53b069559f9c6e318a64fc2984d2f0931101170e60f581e7a1161521e …
```
=> fix: fee limits for LND and LDK, isolated balance calculation

api/api.go, api/models.go, frontend/src/components/channels/ChannelDropdownMenu.tsx, frontend/src/screens/channels/Channels.tsx, frontend/src/types.ts, go.mod, go.sum, lnclient/ldk/ldk.go, lnclient/lnd/lnd.go, lnclient/models.go
partially addresses https://github.com/getAlby/hub/issues/908
also includes vout in funding tx links
=> feat: include funding transaction in pending closing channel message

frontend/src/screens/BackupNode.tsx
Fixes https://github.com/getAlby/hub/issues/893
=> chore: add extra migration warning to ensure users start with a fresh hub

api/api.go, api/backup.go, api/models.go, config/config.go, config/models.go, frontend/src/components/layouts/SettingsLayout.tsx, frontend/src/routes.tsx, frontend/src/screens/BackupNode.tsx, frontend/src/screens/settings/AutoUnlock.tsx, frontend/src/types.ts, http/http_service.go, service/service.go, wails/wails_handlers.go
Closes https://github.com/getAlby/hub/issues/720
Users can optionally save their unlock password to their user_config as plaintext to enable auto start of the node after a machine restart or alby hub update. The unlock password is still required to access the UI.
if the AUTO_UNLOCK_PASSWORD environment variable is set it will overwrite the entry in user_configs.
This feature is only enabled for non-Alby Cloud environments by checking if the default OAuth client is used. Because we do not control other hosting environments (e.g. nodana, and others) there is an additional warning before enabling the feature.
This feature **must be disabled** before backing up the node for migration to ensure that the unlock password is not unintentionally moved to another machine. It also must be disabled …
=> feat: auto unlock

wails/wails_handlers.go
app crashes if tries `Get Node Status` for cashu backend. 
Currently `GetNodeStatus` returns nil and then it tries to dereference that here https://github.com/getAlby/hub/blob/master/wails/wails_handlers.go#L573 causing it to crash. 
Returning an empty object rather than nil.
=> fix: nil dereference in GetNodeStatus of cashu backend

frontend/src/components/ui/tooltip.tsx
Tooltip was appearing too slowly - and if you click then the tooltip does not show.
It is not set to 0 but 200ms, so if your mouse briefly moves past a tooltip, it will not open immediately.
=> fix: shorten tooltip delay duration

scripts/linux-x86_64/update.sh
- add missing newlines
- use pwd to get current absolute directory, remove /albyhub suffix
- add file check to test if user is running in correct directory
=> chore: linux update script improvements

nip47/controllers/get_info_controller.go, nip47/controllers/get_info_controller_test.go
Closes https://github.com/getAlby/hub/issues/785
See example output: https://github.com/getAlby/js-sdk/pull/287
Merges the existing app metadata with two general fields (the id and name of the app)
Allows keysend receive support to be added in getalby.com for accounts that are connected to an Alby Hub subwallet
=> feat: get info metadata

api/api.go, api/models.go, frontend/src/components/layouts/AppLayout.tsx, frontend/src/hooks/useHealthCheck.ts, frontend/src/types.ts, http/http_service.go, lnclient/breez/breez.go, lnclient/cashu/cashu.go, lnclient/greenlight/greenlight.go, lnclient/ldk/ldk.go, lnclient/lnd/lnd.go, lnclient/models.go, lnclient/phoenixd/phoenixd.go, service/models.go, service/service.go, service/start.go, tests/mock_ln_client.go, wails/wails_handlers.go
Closes https://github.com/getAlby/hub/issues/957
Closes https://github.com/getAlby/hub/issues/175
=> feat: health check endpoint

frontend/src/components/SuggestedAppData.tsx, frontend/src/screens/appstore/AppStoreDetail.tsx
Closes https://github.com/getAlby/hub/issues/1008
Copy needs review.
Also commented out nostr.kiwi for now, seems broken.
=> feat: show hub interactions on app store detail pages

frontend/src/components/layouts/AppLayout.tsx
Some adblockers remove sticky elements, and that causes the sidebar to not appear in Safari with ADBlock extension.
This fix replaces it with`fixed` class instead to prevent that from happening. (Also does the same for mobile just-in-case)
=> fix: change sticky to fixed

lnclient/lnd/lnd.go
This causes issues because the payload becomes too large and it is also not related to the node status.
And users run LND elsewhere so it's best to keep it short as they can do debugging in the LND app itself.
=> chore: remove network info and debug info in node status

transactions/payments_test.go, transactions/transactions_service.go
We originally relied on the LNClient to not allow creating duplicate pending transactions, but there seems to be a race condition that allows the creation of two pending transactions in our transactions database. When the payment is settled, only one of the pending transactions is marked as sent, and the other is left pending, which creates issues with budgets and especially sub-wallets (the money is stuck and forever inaccessible)
=> fix: do not allow creating duplicate pending transactions

api/api.go, api/models.go, frontend/src/App.tsx, frontend/src/components/SuggestedAppData.tsx, frontend/src/main.tsx, frontend/src/screens/apps/AppCreated.tsx, frontend/src/types.ts
Part of https://github.com/getAlby/hub/issues/328
The deeplink flow does not work well with a hash router, this will likely break for developers who try to implement it and inject query parameters to configure the new app connection.
We might need to update a few guides, etc. For now I added a redirect to ensure old links still work.
=> fix: new connection deeplink flow

api/api.go, api/models.go, frontend/src/screens/apps/AppCreated.tsx, frontend/src/types.ts
Allows e.g. nostr clients to immediately set a lightning address for receiving payments after connecting via the new nwc deeplink flow.
=> fix: also include lud16 in nwc success event

frontend/src/screens/channels/Channels.tsx, lnclient/ldk/ldk.go
Closes https://github.com/getAlby/hub/issues/1065
This PR stops requiring all users to trust the LSPs to correctly return the correct amount on channel closure (which when channels are closed due to stuck payments they do not), and instead allow the user to choose whether or not they will protect themselves or trust the counterparty. It introduces one extra warning icon to the UI but I think this is important for users to understand.
Tests in mutinynet:
=> fix: replace LDK trusted 0-anchor reserve peers with 0 per channel reserve

api/api.go, lnclient/lnd/lnd.go
When a channel is being opened, health endpoint showsss red saying one or more channels are offline, which is wrong.
Also fixes the wrong calculation of Channel Confs in LND (we don't count the funding tx block currently)
=> fix: offline channel detection in health endpoint

frontend/src/components/home/widgets/NodeStatusWidget.tsx
Fixes #1070
In LND, ListPeers only returns the list of connected peers so this fix will not make a difference there, not sure about LDK.
Channels should be fixed though.
=> fix: show total channels and peers

lnclient/ldk/ldk.go
Fixes https://github.com/getAlby/hub/issues/1073
When we store a lot of payments in VSS it slows down startup a lot, because LDK must fetch all the data one key at a time to build the node. We do not need the old expired payments to be stored by LDK because we also store transactions stored in Alby Hub.
This does set the maximum of invoice expiry to 1 day to ensure we do not remove old payments that are not expired yet. I do not think any service needs longer invoice expiry than one day though?
=> feat: delete old ldk payments

frontend/src/components/TransactionItem.tsx
This fixes the pending transaction icon's bg color
=> fix: pending transaction icon bg color

alby/alby_oauth_service.go, config/config.go, frontend/src/components/FormattedFiatAmount.tsx, frontend/src/screens/settings/Settings.tsx, wails/wails_handlers.go
=> fix: avoid empty currency selector initially

README.md, frontend/src/screens/apps/NewApp.tsx
Fixes https://github.com/getAlby/hub/issues/1108
Minimal change to consistently use msat values. The deep link flow changes were a breaking change and hopefully a spec can be created around this for http-accessible wallets, so it's good to fix this inconsistency now.
=> fix: use msats for deeplink max_amount param to be consistent with NIP-47

frontend/src/screens/peers/ConnectPeer.tsx
Instructing a user to copy and paste connection strings to establish a connection (or channel) is tedious and error-prone. Allowing a service to pass the connection string and a return URL as query parameters simplifies this experience.
Similar to the new app page, a redirect URL (`return_to`) and the connection string (`peer`) can now be passed as query parameters to the new peer page.
Example: https://my.albyhub.com/#/peers/new?peer=03b65c19de2da9d35895b37e6fa263cefbf8d184e6b61c0713747ebf12409d219f%40164.90.241.111%3A9735&return_to=https%3A%2F%2Fwebhook.site%2Fa2a6fd93-0f48-4ef9-8b74-1baf201d4cae
=> feat: add peer and return_to query parameters to peer connection page

lnclient/ldk/ldk.go
Fixes https://github.com/getAlby/hub/issues/1123
rather than setting the node to nil on the lnclient which caused a nil pointer exception if it is accessed while shutting down (which happened when deleting old payments after the node sync finished), use a mutex and shuttingDown boolean to ensure shutdown can only be called once.
=> fix: LDK panic on shutdown due to nil pointer error when deleting old payments

frontend/src/screens/apps/ShowApp.tsx
Adds app creation time to the connection summary card
=> feat: show app creation time in connection summary

frontend/src/components/TransactionsList.tsx
This fixes wallet page (and app connection page) scrolling to the transaction list on every visit.
=> fix: transaction list scrolling on visiting wallet page

frontend/src/screens/channels/Channels.tsx
Currently you have to first manually close the dialog before you can e.g. pay the invoice from this flow.
=> fix: close swap dialogs after opening new window

api/api.go, api/models.go, frontend/src/screens/apps/ShowApp.tsx, frontend/src/types.ts
We were not showing the wallet service pubkey anywhere which is useful info. I also added an alert to show if the app is a legacy one or not. It's not a critical issue, but I think it's nice to know and be able to see.
=> chore: show wallet pubkey on connection page

frontend/src/components/connections/AppCard.tsx, frontend/src/components/connections/AppCardConnectionInfo.tsx, frontend/src/components/connections/AppCardNotice.tsx, frontend/src/hooks/useUnusedApps.ts, frontend/src/routes.tsx, frontend/src/screens/apps/AppList.tsx, frontend/src/screens/apps/AppsCleanup.tsx
A satisfying way to delete apps with one click. Button only shows when the user has more than 5 connections, apps are ordered by unused and then oldest first. Only apps used more than a month ago are considered.
I have many apps I didn't clean up, leading to poor performance especially with firing unnecessary notifications.
=> feat: add app cleanup page

api/api.go
Fixes https://github.com/getAlby/hub/issues/1063
consistently sorts channels - channel capacity first, then spending balance second
=> fix: channels sorting on node page

service/start.go
(Only a part of the problem that the relay performs poorly on restart)
=> fix: still start legacy app subscription when legacy info event fails to be published

frontend/src/components/CloseChannelDialogContent.tsx, frontend/src/components/channels/SwapAlert.tsx, frontend/src/components/channels/SwapDialogs.tsx, frontend/src/screens/channels/Channels.tsx, frontend/src/screens/channels/IncreaseIncomingCapacity.tsx, frontend/src/screens/channels/IncreaseOutgoingCapacity.tsx
Closes https://github.com/getAlby/hub/issues/1134
Adds an alert to swap rather than opening/closing channels in certain relevant places:
- when opening a channel
- when closing a channel
- low receiving capacity on channels page
The alert on other pages will open a link to `/channels?swap=true` which will auto-detect which swap should be used.
Channels page - low receiving capacity
Open new channel pages
Close channel dialog
I'm wondering if we should have a similar alert somewhere to swap in to "top up" channels. Maybe on the receive page?
Copy needs review.
Swap dialogs were moved into a separate file to keep the channels component as small as possible.
=> feat: add swap alert

nip47/publish_nip47_info.go, service/start.go
This is redundant and causes a lot of events to be published on the relay at the same time
=> fix: do not publish info events on relay reconnect

nip47/nip47_service.go, nip47/notifications/nip47_notifier.go, nip47/notifications/nip47_notifier_test.go, service/start.go
we were starting a nip-47 notifier for each subscription rather than once per relay connection.
I also removed some unused dependencies from the notifier.
=> chore: remove duplicated nip-47 notifier

frontend/src/components/channels/ChannelsCards.tsx, frontend/src/components/channels/ChannelsTable.tsx, frontend/src/screens/channels/Channels.tsx
We can point people to check this if they think sats are missing from the spending balance (actually are part of channel reserves)
Fixes https://github.com/getAlby/hub/issues/1159
Alternative to https://github.com/getAlby/hub/pull/1105
=> feat: show total and reserved balance in spending balance tooltip

lnclient/lnd/lnd.go
If you close a channel in LND and stay there, the frontend crashes because `PendingSweepBalancesDetails` is `null` instead of empty array `[]`
=> fix: initialize pending sweep balance to empty slice to avoid null value in frontend

go.mod, go.sum
Part of https://github.com/getAlby/hub/issues/1174
=> fix: reset latest_rgs_snapshot_timestamp on startup if using transient network graph

frontend/src/screens/Home.tsx
Fixes #1208
Just had to change link
=> fix: wrong alby go link used in home screen

frontend/src/screens/wallet/send/PaymentSuccess.tsx
Visiting `/wallet/send/success` page crashes instead of taking to `/wallet/send`. I ran into this on mobile, as often in mobile browsers, the tab refreshes on opening (and it is possible that the tab has last been in success screen)
=> fix: success screen crashes instead of redirecting

frontend/src/screens/channels/Channels.tsx, lnclient/phoenixd/phoenixd.go
Fixes https://github.com/getAlby/hub/issues/1206
I did the same fix as we have for LND, that instead we only fetch the node info once on startup.
In https://github.com/getAlby/hub/pull/1202 we link to the node page, which needs changes for Phoenixd and Cashu so they cannot access channel-related pages/features.
=> fix: alby hub blank screen when phoenixd is offline

frontend/src/components/TransactionItem.tsx
Fixes #1122
~Taken from: https://github.com/iamkun/dayjs/issues/2560#issuecomment-2247454893~ We thought replacing guess with local is better than using a hacky conditional.
=> fix: use local instead of guess

config/config.go
removes excess debug logs and adds error log if the currency actually failed to be fetched
=> fix: error log when fetching currency

api/api.go, frontend/src/components/channels/HealthcheckAlert.tsx, frontend/src/components/layouts/AppLayout.tsx, frontend/src/hooks/useHealthCheck.ts, frontend/src/screens/channels/Channels.tsx, frontend/src/types.ts, frontend/tailwind.config.js, lnclient/phoenixd/phoenixd.go
Closes https://github.com/getAlby/hub/issues/1178
Rather than showing a toast when hovering over the healthcheck, it links to the node page. By default the node page will only show an alert if the healthcheck is failing, however if they click on the green healthcheck indicator, it'll show a success alert.
Now the alby services with incidents will show along with their status, and we link directly to the alby status page and a guide where the user can learn more.
=> feat: link to node page from healthcheck indicator and show healthcheck alert

README.md, nip47/controllers/multi_pay_invoice_controller_test.go, nip47/controllers/multi_pay_keysend_controller_test.go, tests/db/postgres/docker-compose.yml, transactions/transactions_service.go
Alternative to https://github.com/getAlby/hub/pull/1194
=> Fix: postgres pay race condition

lnclient/lnd/lnd.go
Fixes the issue which causes auto unlock to fail in Umbrel/Start 9 on reboot since the `StartApp` call is done while LND is initializing
=> fix: retry start app after failure to avoid downtime in self-hosted LND environments

lnclient/ldk/ldk.go, lnclient/lnd/lnd.go
Fixes https://github.com/getAlby/hub/issues/1197 (LDK only)
Adds new properties to the `nwc_channel_closed` event for both LDK and LND:
```
counterparty_node_url
```
Adds new properties to the `nwc_channel_closed` event to LDK only:
```
pending_balance
funding_tx_id
funding_tx_vout
funding_tx_url
```
CC @MoritzKa (to review the new event properties which we could show in the email)
=> feat: add funding txid and amount to LDK channel closed event

frontend/src/components/CloseChannelDialogContent.tsx, frontend/src/components/channels/ChannelDropdownMenu.tsx, frontend/src/components/channels/SwapAlert.tsx, frontend/src/screens/channels/Channels.tsx
Even if the user has 1 channel there's no need to close it when they could swap instead
=> fix: always show swap alert on close channel dialog

frontend/src/components/MempoolAlert.tsx, frontend/src/screens/wallet/WithdrawOnchainFunds.tsx
Fixes https://github.com/getAlby/hub/issues/1235
also adds a mempool alert shown if the fees are currently high
=> fix: anchor reserve warning not displaying on withdraw on-chain funds page

Dockerfile
Fixes failing `Multiplatform Docker build & push` workflow
=> fix: use go1.23.6 in dockerfile

frontend/src/components/password/PasswordInput.tsx, frontend/src/screens/Start.tsx
When a Start attempt fails (for some node reason let's say) and you try again, you get this weird "invalid password" error even though you haven't changed anything.
It was happening because on receiving an error, the unlockPassword is set to `""` but it is not reflected in the internal state of `PasswordInput` component which makes it render the password without clearing it. This PR syncs it so the component state is updated when value changes externally.
=> fix: sync passwordinput with external value change

Dockerfile
Using `debian:12-slim` instead of `debian` reduces the final container image size while maintaining all required functionality. This helps optimize resource usage and improves pull/push times.
=> chore: use debian:12-slim base image for smaller final container

.github/workflows/wails.yml, Dockerfile, go.mod, go.sum
Closes https://github.com/getAlby/hub/issues/1256
=> chore: bump Go version to 1.24

.github/workflows/http.yml, .github/workflows/wails.yml
See https://github.com/actions/runner-images/issues/11101
=> fix: update workflows to use ubuntu 24.04

frontend/src/components/AppHeader.tsx
Because mobile breakpoint is `768px`
https://github.com/getAlby/hub/blob/3ccdb1e16196bd62ba8463ba400fc0338fce3b6a/frontend/src/hooks/use-mobile.tsx#L3
=> fix: use md breakpoint for sidebar trigger

transactions/payments_test.go, transactions/transactions_service.go
Fixes https://github.com/getAlby/hub/issues/1272
=> fix: filter transactions by state when processing the payment_sent event in the transactions service

frontend/src/components/TransactionItem.tsx, frontend/src/screens/wallet/send/ConfirmPayment.tsx
=> fix: overflow due to long descriptions

api/transactions.go, config/config.go, db/migrations/202504231037_add_indexes.go, db/migrations/migrate.go, nip47/event_handler.go, transactions/transactions_service.go
Fixes #1263
Leaves out a few things mentioned in the issue:
- Persisting a request event and response event (updates are covered though)
- Fetching user config by a particular key (key is already indexed and are very less, not sure why this is happening)
- Listing apps from the http API, the ideal solution is to have the permissions within the apps table, we should do a migration for that)
- `idx_transactions_app_id` (we never filter only on app_id, added composite indexes to cover all cases)
- `idx_transactions_request_event_id` (same as above)
- `idx_transactions_created_at` (same as above)
- `idx_transactions_settled_at` (same as above)
- `idx_transactions_app_id_type_state_created_at_settled_at_payment_hash` (we should always use most differing column first, so it can use the index …
=> feat: improve querying performance

nip47/nip47_service.go, service/create_app_consumer.go, service/update_app_consumer.go
partial workaround for https://github.com/getAlby/hub/issues/1290
part of https://github.com/getAlby/hub/issues/1212
=> fix: re-enqueue failed info publish request

frontend/src/components/AppSidebar.tsx, frontend/src/components/UpdateBanner.tsx, frontend/src/components/layouts/AppLayout.tsx, frontend/src/components/layouts/SettingsLayout.tsx, frontend/src/hooks/useBanner.tsx
Fixes #1250 
- Took [this official example](https://ui.shadcn.com/view/styles/new-york/sidebar-16) as inspo for shifting the sidebar
- Added a `useBanner` hook in which we can change logic if we would like to display other banners (with some conditional logic in `UpdateBanner.tsx`
- Version Shield Icon is removed
- Version will now be displayed in settings
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/b2709f0a-9e50-4627-895e-79927674ce4a"/></td>
<td><img src="https://github.com/user-attachments/assets/7bed363d-7598-40b8-96e6-20a6ddc7556b"/></td>
</tr>
</table>
=> feat: add update banner

frontend/src/components/home/widgets/AppOfTheDayWidget.tsx
It is possible that sometimes apps which already have a standalone widget are featured again in App Of The Day widget, doesn't look that good.
=> chore: filter apps from aotd widget

config/models.go
This change will not affect existing users who have already started their node in the past. Any existing pro users will need to manually enable it in Settings -> Backup.
=> fix: set default vss url to allow enabling vss on self-hosted hubs

api/lsp.go
LNServer is adding 0-conf support, but we must ensure it's only enabled for hubs with 1.17.2 or later, otherwise the channel opening will fail, since LNServer is not a trusted 0 conf peer.
=> fix: pass token to LNServer to indicate 0-conf support

frontend/src/components/home/widgets/LightningMessageboardWidget.tsx, frontend/src/screens/internal-apps/ZapPlanner.tsx
its because of this instances directly give col-span-3 to the <input> tag but after introduction to end adornment for input we wrap input in a div
we should always use
```
<div class="col-span-3">
<input... />
</div>
```
we do it at most of the places expect two screens which i fixed below. also checked all the input instances should be okay now
=> fix: make input full width for zaplanner and messageboard dialogs

frontend/tailwind.config.js
This makes it work in both node v20 and v22
Previously it failed on v22 saying:
```
file:///.../hub/frontend/tailwind.config.js:1
const defaultTheme = require("tailwindcss/defaultTheme");
^
ReferenceError: require is not define
```
=> chore: convert tailwind config to esm

lnclient/ldk/ldk.go
Fixes https://github.com/getAlby/hub/issues/1333
Fixes https://github.com/getAlby/hub/issues/1334
Now we will trigger re-syncs after channel closure or on-chain payment. Also, when a channel is closing with possibly contentious claimable funds, we will use the shortest sync interval to ensure all funds can be claimed before they expire.
We also block doing multiple on-chain transactions without syncing first.
=> fix: trigger LDK re-sync after critical events, block double-spend ononchain withdrawal

frontend/src/components/channels/ChannelsCards.tsx, frontend/src/components/channels/ChannelsTable.tsx, frontend/src/screens/channels/Channels.tsx, frontend/src/screens/channels/CurrentChannelOrder.tsx, frontend/src/screens/channels/IncreaseOutgoingCapacity.tsx, frontend/src/screens/peers/Peers.tsx, frontend/src/types.ts
Closes https://github.com/getAlby/hub/issues/1335
For active, 0-conf channels with 0 confirmations, we do a couple calls to mempool.space to figure out how long the channel has been unconfirmed. If the opening transaction is not in the mempool or has been there longer than an hour, we will show "Unconfirmed" instead of "Online".
=> feat: mark active zero-conf channels as unconfirmed if they haven't been confirmed within an hour

frontend/src/screens/wallet/WithdrawOnchainFunds.tsx
In LND, withdrawing with `TargetConf` set to 1 can make it use very high fees >20-30 sat per vB as it uses mean/median instead of mode (roughly). To avoid that, we set the fees in the frontend itself.
This also adds code to avoid the withdraw page from crashing if the mempool api returns an error, in that case, the user can still input a feeRate or else it will use the `TargetConf: 1`
=> fix: always pass in fee and handle mempool errors

README.md
We spend a lot of time helping users to fix their problems with Raspberry PI installations. That's why it is useful to make the risks clear. 
Furthermore I added a recommendation for desktop installations. Desktops that go offline regularly create a bad UX because payments in external apps are not working and channels are more likely to be closed.
=> Read.me adjustments

nip47/models/transactions.go
Fixes #1429 
Simpler implementation to just return this expired state in NWC, internally we don't change anything as it would complicate unnecessarily.
=> feat: add expired state to nip47 transactions

cmd/http/main.go, lnclient/lnd/lnd.go
Fixes https://github.com/getAlby/hub/issues/1437 by increasing wait time to 30s (should it be 1 minute?) cc @rolznz
And also addresses the issue where hitting `Ctrl+C` doesn't stop the app immediately because the os signal goroutine is registered after service creation.
=> chore: increase lnd wait time before retrying

Dockerfile, README.md, frontend/platform_specific/http/src/utils/request.ts, frontend/src/App.tsx, frontend/src/components/connections/AlbyConnectionCard.tsx, frontend/src/components/layouts/TwoColumnFullScreenLayout.tsx, frontend/src/screens/channels/IncreaseIncomingCapacity.tsx, frontend/src/screens/channels/IncreaseOutgoingCapacity.tsx, frontend/src/screens/channels/auto/AutoChannel.tsx, frontend/src/screens/channels/first/FirstChannel.tsx, frontend/src/screens/subwallets/SubwalletIntro.tsx, frontend/vite.config.ts, scripts/caddy-subpath/Caddyfile, scripts/caddy-subpath/README.md
Fixes https://github.com/getAlby/hub/issues/1025
Followup of https://github.com/getAlby/hub/pull/1393
=> Feat: allow hosting alby hub on subpath

README.md, config/models.go, lnclient/ldk/ldk.go
Fixes #1425
Adds an env var `LDK_MAX_CHANNEL_SATURATION` which is defaulted to `2` (same as LDK)
=> feat: specify max channel saturation power of half from env

go.mod, go.sum
See https://github.com/getAlby/ldk-node/pull/77
=> chore: bump ldk-node to v0.6.1

frontend/src/components/SpendingAlert.tsx, frontend/src/screens/wallet/send/ConfirmPayment.tsx, frontend/src/screens/wallet/send/LnurlPay.tsx
Fixes https://github.com/getAlby/hub/issues/1435
Adds a SpendingAlert component and shows it whenever input/invoice amount is more than `nextMaxSpendableMPP - fee reserve`
=> feat: show alerts if send amount is larger than next spendable mpp

cmd/db_migrate/migrate_test.go, db/db.go, db/migrations/202508041712_delete_non_cascade_deleted_records.go, db/migrations/202508041737_postgres_amount_bigint.go, db/migrations/migrate.go, db/sqlite-wrapper/driver.go, db/test/db_test.go, nip47/controllers/create_connection_controller_test.go, nip47/controllers/multi_pay_invoice_controller_test.go, tests/db/test_db.go, transactions/receive_keysend_test.go, transactions/transactions_service.go
Fixes https://github.com/getAlby/hub/issues/1460
From @rdmitr 
> I have a hunch that multiple sqlite "connections" are opened implicitly, and the PRAGMA ends up being applied to the initial DB connection only. Thing is, Gorm uses the sql package from the Go's standard library, which does internal connection pooling. When it needs a new connection, it uses the driver to open it
I tested this and it turns out to be true. After the change, cascade deletes are working properly again.
I'm not sure why they were working before - maybe a change in gorm since we added the pragma statements.
Applies the SQLITE pragmas to the connection string instead.
Then the existing data needs to be cleaned up to remove orphans (that's the first migration)
I found another issue while migrating my own hub DB to …
=> Fix: sqlite connection parameters, add migrations to delete orphaned records and change postgres transaction amount to bigint

frontend/src/themes/alby.css, frontend/src/themes/bitcoin.css, frontend/src/themes/default.css, frontend/src/themes/nostr.css
=> fix: improve readability of alerts in dark themes

api/api.go, api/models.go, db/migrations/202508041712_delete_non_cascade_deleted_records.go, db/migrations/202508041737_postgres_amount_bigint.go, db/migrations/202508041738_app_last_used.go, db/migrations/migrate.go, db/models.go, frontend/src/components/TransactionItem.tsx, frontend/src/components/connections/AppCardConnectionInfo.tsx, frontend/src/components/home/widgets/LatestUsedAppsWidget.tsx, frontend/src/hooks/useUnusedApps.ts, frontend/src/screens/apps/AppCreated.tsx, frontend/src/screens/apps/AppList.tsx, frontend/src/screens/apps/AppsCleanup.tsx, frontend/src/screens/apps/ShowApp.tsx, frontend/src/types.ts, nip47/event_handler.go
Now that we delete excess request and response events, they are not reliable to be used to show the last used time for the app.
Instead we store it as a timestamp column on the app itself.
=> feat: add app last used time

db/migrations/202508041712_delete_non_cascade_deleted_records.go, service/service.go
Deleting all at once is too slow for hubs that have many events. Instead we will use the background task to slowly remove excess events in batches.
=> fix: remove event deletion from migration

frontend/src/screens/apps/AppCreated.tsx
closes #487 
Now when user clicks on the qr-code, it won't navigate to the blank page (issue was with `<a>` tag) and when user clicks on either on the blurred qr image or reveal qr button, the qr will be revealed. But user need to click on the "copy" button to copy the pairing secret.
=> fix: prevent QR code from opening blank tabs and add click-to-reveal

cmd/http/main.go
It is unclear right now where this is coming from but it's causing the app to be restarted for some of our cloud instances. Possibly it could be due to log forwarding or something on the LDK side (I also saw this with one of our users who had a Breez backend). By ignoring it, it should hopefully trigger an error which can be caught and hopefully we get extra logs as to what caused it in the first place
=> fix: ignore sigpipe signal

frontend/src/screens/apps/ShowApp.tsx, frontend/src/screens/internal-apps/ZapPlanner.tsx
fixes #1533 
Changes:
Added the dropdown menu and `handleConvertToSubwallet` function to convert the isolated app to sub-wallet for the paid users.
=> feat: add convert to sub-wallet button for isolated apps

transactions/notifications_test.go, transactions/transactions_service.go
Fixes https://github.com/getAlby/hub/issues/1587
=> fix: mark pending payment as failed when user has another failed payment with same hash

api/rebalance.go, api/transactions.go, constants/constants.go, lnclient/cashu/cashu.go, lnclient/ldk/ldk.go, lnclient/lnd/lnd.go, lnclient/models.go, lnclient/phoenixd/phoenixd.go, nip47/controllers/pay_invoice_controller.go, swaps/swaps_service.go, tests/mock_ln_client.go, tests/mocks/Config.go, tests/mocks/LNClient.go, tests/mocks/Service.go, transactions/app_payments_test.go, transactions/isolated_app_payments_test.go, transactions/payments_test.go, transactions/self_hold_payments_test.go, transactions/self_payments_test.go, transactions/transactions_service.go
Closes https://github.com/getAlby/hub/issues/1520
Now LDK SendPaymentSync will not return until the payment definitely succeeds or fails.
Both LDK and LND will have ~50-60 seconds to successfully initiate the payment or they will return an error. But if the payment is initiated and stuck along the path or held, there will be no timeout. So things like swaps and hold invoice payments will work as expected.
In the hub UI on the wallet send screen, the payment will also be pending until it definitely succeeds or fails.
Only in NWC (Alby JS SDK) we will return an error after 50 seconds, as it is configured there currently.
Also it is good to remove a decent amount of code :bomb:
=> chore: remove payment timeout

api/api.go, api/models.go, frontend/src/constants.ts, frontend/src/screens/wallet/receive/ReceiveOnchain.tsx, frontend/src/screens/wallet/send/Onchain.tsx, frontend/src/screens/wallet/swap/AutoSwap.tsx, frontend/src/screens/wallet/swap/index.tsx, frontend/src/types.ts, swaps/swaps_service.go
This PR adds fetching swap min and max amounts from the boltz api instead of hardcoding to `50_000` sats
Addresses this [comment](https://github.com/getAlby/hub/pull/1585#discussion_r2272384741)
=> fix: use actual swap limits from boltz api

frontend/src/screens/wallet/index.tsx
Shifts the Send/Receive buttons from the top to under the wallet balance, as per the Alby Hub 2.0 design
<table>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
=> chore: shift send receive buttons in wallet page

api/api.go
Fixes https://github.com/getAlby/hub/issues/1583
Note: only reproducible on postgres.
Tested on sqlite and postgres.
=> fix: order by last used at to order unused apps last

frontend/.husky/commit-msg, frontend/.husky/pre-commit
```
husky - DEPRECATED
Please remove the following two lines from frontend/.husky/commit-msg:
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
They WILL FAIL in v10.0.0
husky - DEPRECATED
Please remove the following two lines from frontend/.husky/pre-commit:
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
They WILL FAIL in v10.0.0
```
=> Fix: husky 10 warning

go.mod, go.sum
Closes https://github.com/getAlby/hub/issues/1610
=> chore: bump ldk-node version to 0.6.2

alby/alby_oauth_service.go
I noticed a request can get stuck and potentially hang forever because the default timeout is **no timeout**.
=> fix: set explicit timeouts of oauth client requests

README.md, api/api.go, api/models.go, cmd/db_migrate/main.go, db/migrations/202508192137_forwards.go, db/migrations/migrate.go, db/models.go, frontend/src/components/RoutingFeeDialogContent.tsx, frontend/src/components/home/widgets/ForwardsWidget.tsx, frontend/src/hooks/useForwards.ts, frontend/src/screens/Home.tsx, frontend/src/types.ts, http/http_service.go, lnclient/ldk/ldk.go, lnclient/lnd/lnd.go, lnclient/lnd/wrapper/lnd.go, lnclient/models.go, service/payment_forwarded_consumer.go, service/service.go, wails/wails_handlers.go
Closes https://github.com/getAlby/hub/issues/1622
Closes https://github.com/getAlby/hub/issues/1604
Currently displayed in the "Stats for nerds" card on the homepage.
TODOs:
Tests:
=> feat: track forwards to display on a home page widget

frontend/src/components/SuggestedAppData.tsx
Change webLink from homepage to specific extension page.
Now the users will be able to jump right into the extension download page when clicking on the weblink in both places mentioned in the issue.
=> fix: optimize App Store Alby Extension download flow (#1624)

frontend/src/components/AppSidebar.tsx
Later this could be "Upgrade" and also recommend Alby Cloud?
=> fix: remove Alby Cloud sidebar link

README.md, api/api.go, api/models.go, frontend/src/screens/wallet/swap/SwapOutStatus.tsx, frontend/src/types.ts, swaps/swaps_service.go
Tested normal swaps, auto swap (to pubkey), auto swap (to xpub)
=> fix: auto swap to xpub

frontend/src/components/CommandPalette.tsx
Unfortunately the command component is a bit buggy and doesn't seem to handle dynamic commands well :confused:  so it's not perfect. I had to hide the empty state as it incorrectly shows empty even if it finds an app, and sometimes the focus is wrong so I put the connected apps at the bottom of the list.
=> feat: display apps in command palette

swaps/swaps_service.go
Fixes #1669
We used to wait for `TransactionClaimed` state before which is sent when Boltz successfully claims the bitcoin onchain. I think the best thing to do is to listen on `InvoicePaid` state as that would be in sync with the Hub's state (in transactions list)
=> fix: use InvoicePaid state to mark swap in success

frontend/src/screens/channels/IncreaseIncomingCapacity.tsx
Fixes https://github.com/getAlby/hub/issues/1696
=> fix: filter out suggestions that do not allow public channels if the order is for a public channel

frontend/src/components/channels/SwapAlert.tsx, frontend/src/screens/channels/IncreaseIncomingCapacity.tsx, frontend/src/screens/channels/IncreaseOutgoingCapacity.tsx
This fixes wrong swap alerts being shown based on balance info in both incoming/outgoing channel screens.
=> fix: set direction in swap alert

frontend/src/screens/channels/IncreaseIncomingCapacity.tsx, frontend/src/screens/channels/first/FirstChannel.tsx
Closes https://github.com/getAlby/hub/issues/1691
Added to the first channel flow and the manual incoming channel flow
=> chore: add note about channels being non-refundable

api/rebalance.go, api/transactions.go, lnclient/cashu/cashu.go, lnclient/ldk/ldk.go, lnclient/lnd/lnd.go, lnclient/models.go, lnclient/phoenixd/phoenixd.go, nip47/controllers/make_invoice_controller.go, swaps/swaps_service.go, tests/mock_ln_client.go, tests/mocks/LNClient.go, transactions/make_invoice_test.go, transactions/transactions_service.go
Fixes https://github.com/getAlby/hub/issues/1712
For some reason even when providing a single route hint, LND is generating 2 route hints in the invoice (and the original issue was that the LND invoice was only including one route hint which was causing rebalancing to not work)
However I opened another channel and tested rebalancing into all channels, and it always includes the correct route hint (+ another one, seems random). I opened a 4th channel and also always includes the correct hint for the channel I want to rebalance into. So it seems to be working.
How to test: log the invoice created in the rebalance function and then return an error (instead of actually doing the rebalance, which will fail since we're running regtest in polar)
=> feat: rebalance through node pubkey

frontend/src/components/AnchorReserveAlert.tsx, frontend/src/screens/wallet/receive/ReceiveOnchain.tsx, frontend/src/screens/wallet/swap/SwapInStatus.tsx, frontend/src/screens/wallet/swap/index.tsx
Fixes https://github.com/getAlby/hub/issues/1695
https://github.com/user-attachments/assets/1e3a374b-464e-4112-9dad-878d187c2cb8
With reference to this [comment](https://github.com/getAlby/hub/issues/1695#issuecomment-3312101834), I found the Anchor reserve alert componet , whiich get triggered when user tries to use the onchain balance, that leaves less than 50k sats on-chain and not 25k , Let me know if that needs to be changed or this works. 
Thanks!
=> fix(UX): Alert users about anchor-reserve when they try to use their max on-chain balance

frontend/src/screens/subwallets/SubwalletList.tsx
=> fix: remove card description for Sub-Wallets

frontend/src/screens/apps/NewApp.tsx
Fixes https://github.com/getAlby/hub/issues/1742
This also fixes a bug @rolznz discovered which happens because the event dispatch happens in the finalize component which is wrong. It is now shifted so that we dispatch the event right after the app creation.
=> fix: remove finalize step in 1 click flow

frontend/src/components/TransactionItem.tsx
Adds the fee percentage to the transaction detail dialog:
=> fix: add transaction fee percentage
