- alby/models.go
- frontend/src/screens/channels/IncreaseIncomingCapacity.tsx
- frontend/src/screens/channels/IncreaseOutgoingCapacity.tsx
- frontend/src/types.ts
See https://github.com/getAlby/nostr-wallet-connect-next/pull/561
> Feat: include LSPS1 maximum channel size in frontend

- frontend/src/routes.tsx
> fix: default redirect on settings route

- frontend/src/lib/clipboard.ts
- frontend/src/screens/apps/AppCreated.tsx
Fixes #56 
Tested on a local domain.
> fix: make copy to clipboard work in non-https environments

- frontend/src/components/SidebarHint.tsx
- frontend/src/screens/onboarding/MigrateAlbyFunds.tsx
- frontend/src/screens/wallet/OnboardingChecklist.tsx
Fixes https://github.com/getAlby/hub/issues/20
> fix: link to open first channel when alby shared funds are available

- lnclient/ldk/ldk.go
Fixes https://github.com/getAlby/hub/issues/261
> fix: add central LDK gossip node to help gossip new public channels

- frontend/src/components/SidebarHint.tsx
- frontend/src/screens/wallet/OnboardingChecklist.tsx
Fixes https://github.com/getAlby/hub/issues/259
> fix: links to open first channel in sidebar and onboarding checklist

- frontend/src/components/layouts/SettingsLayout.tsx
- frontend/src/screens/BackupNode.tsx
Fixes https://github.com/getAlby/hub/issues/263
> feat: improve migrate node UI

- lnclient/lnd/lnd.go
> fix: change mainnet to bitcoin

- frontend/src/screens/channels/Channels.tsx
- frontend/src/screens/wallet/OnboardingChecklist.tsx
- Allow only the next item to be clicked, disable everything else
- Add numbers
> feat: onboarding checklist 

- README.md
correct mis-spelling of phoenixd
> fix typo - README.md

- frontend/src/screens/setup/ImportMnemonic.tsx
Fixes #311 
@rolznz Not sure if we really need to explain what could go wrong in detail, I think it's okay to just have this warning in there?
> fix: add warning for importing your mnemonic

- frontend/src/screens/channels/Channels.tsx
> fix: show channel status for opening channels

- alby/alby_oauth_service.go
- events/models.go
- lnclient/ldk/ldk.go
- lnclient/lnd/lnd.go
- transactions/notifications_test.go
- transactions/transactions_service.go
Fixes incorrect properties being passed to Alby OAuth service, and includes reason in event
> fix: nwc payment failed async event properties

- frontend/src/components/TransactionItem.tsx
> fix: break long descriptions

- frontend/src/hooks/useRedeemOnchainFunds.ts
- frontend/src/screens/channels/Channels.tsx
Fixes https://github.com/getAlby/hub/issues/335
> fix: improve copy and add confirmation on redeem onchain funds

- frontend/src/components/layouts/AppLayout.tsx
Fixes https://github.com/getAlby/hub/issues/288
> feat: add guides link

- db/migrations/202407262257_remove_invalid_scopes.go
- db/migrations/migrate.go
- frontend/src/types.ts
Fixes https://github.com/getAlby/hub/issues/348
> fix: remove app permissions with invalid scopes

- frontend/src/hooks/useOnchainAddress.ts
- frontend/src/screens/channels/CurrentChannelOrder.tsx
Fixes https://github.com/getAlby/hub/issues/296
> fix: do not change deposit address after depositing funds on current channel order page

- frontend/src/components/EmptyState.tsx
- frontend/src/screens/channels/first/OpeningFirstChannel.tsx
> feat: opening channel empty state

- lnclient/ldk/ldk.go
> fix: keep anchor reserves when withdrawing savings balance

- frontend/src/components/connections/AppCardConnectionInfo.tsx
> fix: adds last used date to all card variants

- .env.example
- frontend/src/screens/channels/Channels.tsx
- lnclient/ldk/ldk.go
Fixes https://github.com/getAlby/hub/issues/382
- do not show forwarding fee error if channel is opening
- remove alert for low spending capacity
> fix: channel warnings

- frontend/src/components/layouts/AppLayout.tsx
> chore: change hub update link

- go.mod
- go.sum
See https://github.com/getAlby/ldk-node/pull/45
> chore: update ldk-node-go dependency

- transactions/transactions_service.go
Fixes https://github.com/getAlby/hub/issues/406
> fix: order transactions by settled at and then created at

- alby/models.go
- frontend/src/screens/settings/DeveloperSettings.tsx
- frontend/src/types.ts
- frontend/tailwind.config.js
Fixes https://github.com/getAlby/hub/issues/445
> feat: add extra api header for hosted apps

- transactions/receive_keysend_test.go
- transactions/transactions_service.go
> fix: keysend custom value decoding

- frontend/src/components/TransactionItem.tsx
> fix: transaction list styles

- frontend/package.json
- frontend/yarn.lock
Fixes https://github.com/getAlby/hub/issues/480
> fix: bump bitcoin connect dependency to fix csp issue with invoice qr

- frontend/src/components/layouts/TwoColumnFullScreenLayout.tsx
> chore: change back button variant to outline

- lnclient/ldk/ldk.go
Fixes https://github.com/getAlby/hub/issues/526
> fix: ldk log level

- api/api.go
- api/models.go
- frontend/src/types.ts
Fixes #460
Returns app id in `CreateAppRepsonse`
> chore: add app id to CreateAppRepsonse

- frontend/src/screens/setup/node/CashuForm.tsx
- lnclient/cashu/cashu.go
Fixes https://github.com/getAlby/hub/issues/532
> fix: use a public cashu default mint

- frontend/src/components/channels/ChannelWaitingForConfirmations.tsx
- frontend/src/screens/channels/CurrentChannelOrder.tsx
- frontend/src/screens/channels/first/OpeningFirstChannel.tsx
fixes https://github.com/getAlby/hub/issues/398
> feat: use better channel opening design in manual channel open flow

- alby/alby_oauth_service.go
Fixes https://github.com/getAlby/hub/issues/529
> fix: remove oauth errors on first start

- README.md
otherwise docker might cache the image
> docs: always pull image with docker

- frontend/src/screens/setup/SetupPassword.tsx
Fixes https://github.com/getAlby/hub/issues/500
> feat: add extra password confirmation on setup password page

- .github/workflows/http.yml
- build/darwin/http/gon-notarize.json
> feat: generate macos http build in actions

- service/start.go
see https://stackoverflow.com/questions/65213707/where-to-put-wg-add
> chore: wg.Add() before go

- .github/workflows/http.yml
- .github/workflows/wails.yml
fixes https://github.com/getAlby/hub/issues/562
> chore: run extra workflows on PR

- .env.example
- README.md
- config/models.go
- service/service.go
Closes https://github.com/getAlby/hub/issues/84
> feat: auto unlock on startup

- api/api.go
- api/models.go
- fly.toml
- frontend/src/screens/Start.tsx
- frontend/src/screens/setup/SetupFinish.tsx
- frontend/src/types.ts
- http/http_service.go
- service/models.go
- service/service.go
Fixes #545 
https://github.com/user-attachments/assets/a986347d-dab4-497a-aee9-830dc2f24a57
https://github.com/user-attachments/assets/15e445e4-6d4d-48df-9ddf-b044f8163668
> feat: show startup error

- frontend/src/screens/internal-apps/BuzzPay.tsx
Trying to make it clear that the link needs to be copied and opend on the different devices
> chore: new BuzzPay PoS flow

- frontend/src/screens/internal-apps/UncleJim.tsx
> chore: jim: text and addition option for other apps

- frontend/src/hooks/useDeleteApp.ts
- frontend/src/screens/apps/ShowApp.tsx
> fix: delete connection copy

- frontend/src/screens/setup/SetupAdvanced.tsx
- frontend/src/screens/setup/SetupPassword.tsx
Fixes https://github.com/getAlby/hub/issues/636
> fix: import mnemonic from advanced setup does not set ldk backend type

- frontend/src/screens/apps/AppList.tsx
> chore: order apps by last used

- frontend/src/components/connections/AppCardConnectionInfo.tsx
- frontend/src/screens/apps/ShowApp.tsx
> chore: do not round connection balance

- frontend/src/screens/channels/CurrentChannelOrder.tsx
Tried to apply this issue https://github.com/getAlby/hub/issues/663
> Fix copy on onchain deposit

- frontend/src/components/AuthCodeForm.tsx
> fix: add re-request button in alby auth screen

- lnclient/ldk/ldk.go
Fixes https://github.com/getAlby/hub/issues/646
This is only done for LDK so I decided to add this logic directly in the LDK implementation.
I don't think we take responsibility for LND - that should be done by LND itself?
$ cat .data/ldk/static_channel_backups/2024-09-21T13\:57\:48+07\:00.json 
```json
[{"channel_id":"e3bed0e8ae812f5712c02e6b0fee261f04881d5034db446414eec28d643d0f0e","node_id":"02419a12598b7bfd2ce33769ad850a3a0d3ae0b9e7a5493780ac2b4ac682090bd3","peer_id":"032ae843e4d7d177f151d021ac8044b0636ec72b1ce3ffcde5c04748db2517ab03","channel_size":1000000,"funding_tx_id":"0e0f3d648dc2ee146444db34501d88041f26ee0f6b2ec012572f81aee8d0bee3","funding_tx_vout":0},{"channel_id":"1d05be99c206e8ea8d5a18cb39568b42d015b9b5e99da3d783403214227a10da","node_id":"02419a12598b7bfd2ce33769ad850a3a0d3a …
```
> feat: save LDK static channel backups to disk

- api/backup.go
Add extra logs to search for to know if a backup or migration happened
> chore: add extra migration backup logs

- frontend/src/screens/internal-apps/UncleJim.tsx
Fixes #756 
- Unfold the first option
- Remove duplicate copy
> fix: simplify friends & family app

- lnclient/ldk/ldk.go
Fixes https://github.com/getAlby/hub/issues/691
> chore: update ldk backend to use json logging where it was not

- alby/alby_oauth_service.go
Fixes https://github.com/getAlby/hub/issues/810
> chore: add relay url to create alby account node request

- frontend/src/screens/channels/Channels.tsx
Fixes https://github.com/getAlby/hub/issues/676
> feat: add withdraw button to savings balance card

- transactions/app_payments_test.go
- transactions/isolated_app_payments_test.go
- transactions/transactions_service.go
Fixes https://github.com/getAlby/hub/issues/638
> feat: include invoice description in nwc payment permission denied event message

- frontend/src/components/layouts/AppLayout.tsx
> feat: reorder app layout links and update icons for app store and connections

- frontend/src/screens/channels/ChannelPublicPrivateAlert.tsx
- frontend/src/screens/channels/IncreaseIncomingCapacity.tsx
- frontend/src/screens/channels/IncreaseOutgoingCapacity.tsx
- frontend/src/screens/channels/auto/AutoChannel.tsx
Fixes https://github.com/getAlby/hub/issues/58
> feat: add warning if opening conflicting public or private channels

- frontend/src/components/layouts/ReceiveLayout.tsx
- frontend/src/components/layouts/SendLayout.tsx
- frontend/src/routes.tsx
- frontend/src/screens/wallet/Receive.tsx
- frontend/src/screens/wallet/receive/ReceiveInvoice.tsx
- frontend/tailwind.config.js
Fixes https://github.com/getAlby/hub/issues/595
> feat: receive via lightning address

- config/config.go
Fixes https://github.com/getAlby/hub/issues/800
> fix: Always update LND certificate

- api/transactions.go
- nip47/controllers/multi_pay_invoice_controller.go
- nip47/controllers/pay_invoice_controller.go
- nip47/controllers/pay_invoice_controller_test.go
- transactions/app_payments_test.go
- transactions/isolated_app_payments_test.go
- transactions/payments_test.go
- transactions/self_payments_test.go
- transactions/transactions_service.go
Closes https://github.com/getAlby/hub/issues/784
> feat: add metadata property to pay_invoice

- nip47/event_handler.go
- nip47/event_handler_test.go
Fixes https://github.com/getAlby/hub/issues/814
> fix: ignore old payment and invoice requests

- frontend/src/screens/Home.tsx
Updated copy on Alby Account
Fixed link to Alby Extension
> Small updates to  Home Screen

- lnclient/ldk/ldk.go
- service/start.go
Closes https://github.com/getAlby/hub/issues/53
> chore: remove old scb restore code (moved to hub-recovery tool)

- frontend/package.json
- frontend/src/screens/wallet/send/ZeroAmount.tsx
- frontend/yarn.lock
- lnclient/lnd/lnd.go
Adds 0 amount invoices for LND
> feat: pay 0 amount invoices in LND

- README.md
The important change is `512GB` to `512MB` RAM 😁
> Fix typo on readme requirements

- frontend/src/components/CloseChannelDialogContent.tsx
> chore: change channel closure copy

- frontend/src/screens/Home.tsx
> fix: browser extension card spacing

- frontend/src/App.tsx
- frontend/src/components/ui/tooltip.tsx
- frontend/src/screens/channels/Channels.tsx
Fixes https://github.com/getAlby/hub/issues/399
Also fixes minor spacing issue on node page in mobile view
> fix: tooltips on mobile

- frontend/package.json
- frontend/src/components/PayLightningInvoice.tsx
- frontend/src/components/QRCode.tsx
- frontend/src/screens/channels/CurrentChannelOrder.tsx
- frontend/src/screens/channels/auto/AutoChannel.tsx
- frontend/src/screens/wallet/Receive.tsx
- frontend/tailwind.config.js
- frontend/yarn.lock
Fixes https://github.com/getAlby/hub/issues/878
Dark QR codes have been replaced with always using a white background. All QR codes have been updated to use our internal component, and bitcoin-connect QR codes have been removed.
> fix: dark qr codes and remove bitcoin connect

- frontend/src/components/layouts/AppLayout.tsx
> feat: update icons and reorder sidebar elements

- config/config.go
Fixes https://github.com/getAlby/hub/issues/862
> fix: allow changing relay

- alby/alby_oauth_service.go
Fixes https://github.com/getAlby/hub/issues/530
> chore: use whitelist for alby events

- frontend/src/screens/channels/Channels.tsx
- frontend/src/types.ts
- lnclient/ldk/ldk.go
- lnclient/lnd/lnd.go
- lnclient/models.go
Fixes https://github.com/getAlby/hub/issues/911
> feat: balance details for pending channel closures

- frontend/src/screens/wallet/WithdrawOnchainFunds.tsx
> feat: fix dialog overflows

- lnclient/ldk/ldk.go
Fixes https://github.com/getAlby/hub/issues/818
> feat: implement router reset through the LDK-node Builder

- alby/alby_oauth_service.go
- lnclient/ldk/ldk.go
Fixes https://github.com/getAlby/hub/issues/772
> chore: add 3 retries for static channels backup, remove scb backup from node start

- frontend/src/screens/channels/Channels.tsx
Closes https://github.com/getAlby/hub/issues/482
Only works with a mainnet invoice.
> feat: add boltz swap in dialog

- frontend/src/components/TransactionItem.tsx
> feat: update transaction icon colors

- apps/apps_service.go
- frontend/src/components/SuggestedAppData.tsx
- frontend/src/screens/internal-apps/UncleJim.tsx
Closes https://github.com/getAlby/hub/issues/883
> Rename subaccount to sub-wallet

- alby/models.go
- frontend/src/screens/channels/ChannelPeerNote.tsx
- frontend/src/screens/channels/IncreaseIncomingCapacity.tsx
- frontend/src/screens/channels/IncreaseOutgoingCapacity.tsx
- frontend/src/types.ts
This allows us to alert users of important info about certain channel partners. Shows on both incoming and outgoing flows.
The UI/UX could be improved, it's a bit difficult because by default the user is not informed of who they open a channel with unless they open the advanced options.
> feat: display channel note above open channel buttons on increase incoming/outgoing flows

- api/models.go
- api/transactions.go
- frontend/src/components/TransactionItem.tsx
- frontend/src/types.ts
> feat: show failure reason on transaction modal in transaction list

- frontend/src/screens/appstore/AppStore.tsx
Instead of Jotform (that is used for /discover) let's utilize that wiki for contributors: https://github.com/getAlby/hub/wiki/How-to:-submit-new-app-to-Hub's-Store
> Update "+ Submit your app" link

- frontend/src/screens/wallet/WithdrawOnchainFunds.tsx
> fix: do not show 0 in withdraw alert

- service/create_app_consumer.go
- service/start.go
Fixes https://github.com/getAlby/hub/issues/998
> chore: suppress error logs on shutdown

- frontend/src/screens/channels/IncreaseIncomingCapacity.tsx
- frontend/src/screens/channels/IncreaseOutgoingCapacity.tsx
> fix: conflict warning is not removed on switching

- frontend/src/screens/BackupMnemonic.tsx
> fix copy: Update BackupMnemonic.tsx

- frontend/src/components/home/widgets/LatestUsedAppsWidget.tsx
- Text on cards was bigger than the heading, which disturbs the hierarchy
- Filter apps without any events
> fix: improve recently used apps card

- service/start.go
Fixes https://github.com/getAlby/hub/issues/1076
Marking the relay as online was never reached if we started the legacy app wallet subscription since it's a blocking method.
The start app wallet subscription method has been moved to a goroutine to not block the loop.
> fix: relay always offline for hubs with legacy subscription

- frontend/src/screens/channels/Channels.tsx
- frontend/src/types.ts
- go.mod
- go.sum
- lnclient/ldk/ldk.go
- lnclient/models.go
- utils/utils.go
Fixes https://github.com/getAlby/hub/issues/1026
> feat: return pending sweep balance details in LDK

- frontend/src/components/FormattedFiatAmount.tsx
- frontend/src/components/layouts/AppLayout.tsx
- frontend/src/screens/wallet/index.tsx
> feat: show fiat amount on wallet screen

- .github/workflows/wails.yml
Fixes https://github.com/getAlby/hub/issues/948
> fix: dedicated Wails build for Ubuntu 24.04 to work around libwebkit2gtk-4.1 incompatibility

- config/config.go
> fix: remove lnd certificate from user config if not provided

- nip47/controllers/create_connection_controller.go
Also converts budget renewal to lowercase before checking
> fix: convert budget from msats to sats

- nip47/controllers/create_connection_controller_test.go
- nip47/controllers/get_balance_controller_test.go
- nip47/controllers/get_budget_controller_test.go
- nip47/controllers/get_info_controller.go
- nip47/controllers/get_info_controller_test.go
- nip47/controllers/list_transactions_controller_test.go
- nip47/controllers/lookup_invoice_controller_test.go
- nip47/controllers/make_invoice_controller_test.go
- nip47/controllers/multi_pay_invoice_controller_test.go
- nip47/controllers/multi_pay_keysend_controller_test.go
- nip47/controllers/nip47_controller.go
- nip47/controllers/pay_invoice_controller_test.go
- nip47/controllers/pay_keysend_controller_test.go
- nip47/event_handler.go
(Almost all of it is just updating tests, see `get_info_controller.go`)
> Feat: add lud16 to get_info response

- frontend/src/components/FormattedFiatAmount.tsx
- frontend/src/components/TransactionItem.tsx
- frontend/src/components/ui/skeleton.tsx
- frontend/src/screens/wallet/index.tsx
- Fix layout shifts due to different heights
- Use shadcn Skeleton component
- Make loading animation work for different text sizes
- Some more responsive improvements
> fix: skeleton component

- frontend/src/screens/apps/AppCreated.tsx
Related to https://github.com/getAlby/hub/issues/1140
> fix: add connected state for connect app card

- frontend/src/screens/internal-apps/AlbyGo.tsx
Fixes https://github.com/getAlby/hub/issues/1140
This should have been done from the beginning :grinning:
> fix: redirect to app created page after creating alby go app with one tap connections

- lnclient/ldk/ldk.go
Fixes https://github.com/getAlby/hub/issues/1113
> fix: disconnect ldk peer before re-connecting

- config/config.go
Fixes https://github.com/getAlby/hub/issues/1118
> fix: do not allow changing unlock password to an empty password

- README.md
- alby/alby_oauth_service.go
- lnclient/ldk/ldk.go
Fixes https://github.com/getAlby/hub/issues/1154
> feat: backup LDK channels after connecting alby account

- frontend/src/components/TransactionItem.tsx
- frontend/src/screens/wallet/index.tsx
Fixes various font styles on wallet & transaction list
> fix: font styles

- db/migrations/202407201604_transactions_indexes.go
- frontend/src/components/CloseChannelDialogContent.tsx
- frontend/src/components/RoutingFeeDialogContent.tsx
- frontend/src/components/home/widgets/LightningMessageboardWidget.tsx
- frontend/src/screens/internal-apps/ZapPlanner.tsx
- http/http_service.go
- lnclient/lnd/lnd.go
- lnclient/phoenixd/phoenixd.go
- nip47/event_handler.go
> chore: fix some typos

- frontend/src/components/layouts/AppLayout.tsx
Guides, Feedback board and support options will be linked from support.getalby.com
> fix: cleanup sidebar

- lnclient/lnd/lnd.go
Fixes https://github.com/getAlby/hub/issues/684
Sets the target conf to 1 so LND can adjust the fee accordingly to process the tx ASAP ⚡
> fix: set target conf to 1 while withdrawing

- go.mod
- go.sum
Fixes https://github.com/getAlby/hub/issues/1172
> chore: update LDK-node with exponential peer reconnect backoff

- frontend/src/components/ResetRoutingDataDialogContent.tsx
- lnclient/ldk/ldk.go
Fixes https://github.com/getAlby/hub/issues/1179 (hopefully)
> fix: nil pointer when getting network graph

- frontend/src/components/home/widgets/LatestUsedAppsWidget.tsx
Fixes text overflowing in apps widget.
> fix: text overflowing in used apps widget

- frontend/platform_specific/http/src/utils/openLink.ts
https://stackoverflow.com/questions/20696041/window-openurl-blank-not-working-on-imac-safari
> fix: open links from async functions on ios

- frontend/src/components/home/widgets/WhatsNewWidget.tsx
> feat: add update button to what's new widget

- docker-compose.yml
Fixes https://github.com/getAlby/hub/issues/1192
> fix: do not explicitly set platform in docker compose file

- frontend/src/screens/MigrateNode.tsx
> chore: remove redundant word

- frontend/src/screens/apps/ShowApp.tsx
> fix: wallet pubkey text wrapping

- frontend/src/components/SuggestedApps.tsx
> fix: remove links from app store overview

- scripts/linux-aarch64/install.sh
- scripts/linux-aarch64/update.sh
- scripts/linux-x86_64/install.sh
- scripts/linux-x86_64/update.sh
- scripts/pi-aarch64/install.sh
- scripts/pi-aarch64/update.sh
- scripts/pi-arm/install.sh
- scripts/pi-arm/update.sh
- scripts/verify.sh
Fixes https://github.com/getAlby/hub/issues/1133
**Before merging ensure verify.sh can be fetched from getalby.com** :heavy_check_mark:  https://getalby.com/install/hub/verify.sh
> feat: verify package signatures

- swaps/swaps_service.go
> fix: use short lived context to make payment

- frontend/src/components/ResponsiveButton.tsx
- frontend/src/components/ui/alert.tsx
- frontend/src/routes.tsx
- frontend/src/screens/subwallets/NewSubwallet.tsx
- frontend/src/screens/subwallets/SubwalletIntro.tsx
- frontend/src/screens/subwallets/SubwalletList.tsx
Fixes https://github.com/getAlby/hub/issues/1091
Improvements to the Subwallets screen
> feat: sub wallet improvements

- frontend/src/components/UserAvatar.tsx
- frontend/src/components/layouts/ReceiveLayout.tsx
- frontend/src/screens/wallet/Receive.tsx
- frontend/src/screens/wallet/receive/ReceiveInvoice.tsx
Fixes https://github.com/getAlby/hub/issues/816
<table>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
> feat: receive ui improvements

- frontend/src/components/SidebarHint.tsx
- frontend/src/constants.ts
- frontend/src/hooks/useOnboardingData.ts
- frontend/src/screens/Home.tsx
- frontend/src/screens/alby/SupportAlby.tsx
> fix: support alby

- go.mod
- go.sum
- lnclient/ldk/ldk.go
- lnclient/ldk/ldk_logger.go
Closes https://github.com/getAlby/hub/issues/1275
Closes https://github.com/getAlby/hub/issues/946
TODOs:
> feat: update to LDK-node v0.5.0

- fly.toml
- lnclient/ldk/ldk.go
> chore: increase node shutdown timeout

- api/api.go
- api/models.go
- frontend/src/components/channels/OnchainTransactionsTable.tsx
- frontend/src/hooks/useOnchainTransactions.ts
- frontend/src/screens/channels/Channels.tsx
- frontend/src/types.ts
- go.mod
- go.sum
- http/http_service.go
- lnclient/cashu/cashu.go
- lnclient/ldk/ldk.go
- lnclient/ldk/ldk_logger.go
- lnclient/lnd/lnd.go
- lnclient/models.go
- lnclient/phoenixd/phoenixd.go
- tests/mock_ln_client.go
- tests/mocks/LNClient.go
- wails/wails_handlers.go
Closes https://github.com/getAlby/hub/issues/1291
Note: createdAt is not set right now, only updatedAt is used in the UI. (See https://github.com/getAlby/ldk-node/issues/69). It's a custom field implemented by Alby inside ldk-node (maybe we don't need it really)
TODOs:
> Feat: Add Onchain transactions to node page

- frontend/src/screens/channels/auto/AutoChannel.tsx
> chore: change incoming liquidity to receiving capacity

- api/api.go
- api/models.go
- frontend/src/components/layouts/SettingsLayout.tsx
- frontend/src/routes.tsx
- frontend/src/screens/settings/About.tsx
- frontend/src/types.ts
> feat: add info page to settings

- frontend/src/components/home/widgets/SupportAlbyWidget.tsx
- frontend/src/constants.ts
- frontend/src/screens/Home.tsx
- frontend/src/screens/settings/Swaps.tsx
> fix: remove duplicate fee mention from header

- frontend/src/screens/subwallets/SubwalletIntro.tsx
> chore: fix typo

- lnclient/ldk/ldk.go
> chore: add lnserver wave to trusted peers for 0 conf

- go.mod
- go.sum
Fixes https://github.com/getAlby/hub/issues/1326
> chore: bump rust lightning to 0.1.4

- frontend/src/components/mnemonic/MnemonicInputs.tsx
MnemonicInput component imports RevealPasswordToggle component with wrong name. just corrected that
> fix: rename component import

- go.mod
- go.sum
- lnclient/ldk/ldk.go
Closes https://github.com/getAlby/hub/issues/1397
See https://github.com/getAlby/ldk-node/pull/73
> chore: bump LDK-node to v0.6.0

- frontend/src/screens/wallet/Send.tsx
Fixes https://github.com/getAlby/hub/issues/1422
> fix: only try pay to lightning address if the recipient is a lightning address

- api/rebalance.go
- frontend/src/components/RebalanceChannelDialogContent.tsx
- frontend/src/components/channels/ChannelDropdownMenu.tsx
- frontend/src/screens/wallet/swap/SwapOutStatus.tsx
Addresses feedback in https://github.com/getAlby/hub/pull/1364
> chore: minor copy changes, remove unnecessary metadata field

- service/service.go
Fixes https://github.com/getAlby/hub/issues/1485
> fix: limit number of deleted events, remove duplicated service shutdown

- frontend/src/screens/internal-apps/Goose.tsx
Closes https://github.com/getAlby/hub/issues/1473
> chore: update goose app to use http streamable mcp protocol

- frontend/src/components/channels/ChannelDropdownMenu.tsx
Fixes https://github.com/getAlby/hub/issues/1488
> fix: properly close dialog after rebalancing

- .env.example
- alby/alby_oauth_service.go
- config/models.go
- docker-compose.yml
- render.yaml
- scripts/linux-aarch64/install.sh
- scripts/linux-x86_64/install.sh
- scripts/linux-x86_64/phoenixd/docker-compose.yml
- scripts/linux-x86_64/phoenixd/install.sh
- scripts/linux-x86_64/phoenixd/render.yaml
- scripts/pi-aarch64/install.sh
- scripts/pi-arm/install.sh
Fixes https://github.com/getAlby/hub/issues/764
> chore: rename LOG_EVENTS env variable

- frontend/src/screens/settings/DebugTools.tsx
- swaps/swaps_service.go
fixes https://github.com/getAlby/hub/issues/1513
> fix: only allow refunding onchain -> lightning swaps

- lnclient/lnd/lnd.go
- swaps/swaps_service.go
Fixes https://github.com/getAlby/hub/issues/1514
TODO:
> fix: ignore swap out payment timeout

- service/start.go
Fixes https://github.com/getAlby/hub/issues/1565
Tested on LDK
> fix: stop autoswaps on shutting down ln client

- frontend/src/components/SuggestedAppData.tsx
Fixed URL Typo for wave.space app
> Fixed App-URL Typo in SuggestedAppData.tsx

- README.md
- config/models.go
- lnclient/ldk/ldk.go
Closes https://github.com/getAlby/hub/issues/1599
> feat: add environment variable to configure LDK announcement addresses

- frontend/src/screens/wallet/send/PaymentSuccess.tsx
- frontend/src/screens/wallet/send/ZeroAmount.tsx
> fix: show payment amount on zero amount success screen

- service/start.go
Fixes https://github.com/getAlby/hub/issues/1611
> chore: set user agent while connecting to relay

- nip47/nip47_service.go
- nip47/publish_nip47_info.go
- service/create_app_consumer.go
- service/start.go
- service/update_app_consumer.go
Closes https://github.com/getAlby/hub/issues/1591
> chore: lookup app by id instead of wallet pubkey when publishing nip47 info

- frontend/src/screens/wallet/send/ZeroAmount.tsx
Fixes https://github.com/getAlby/hub/issues/1655
> fix: amount not passed in request from zero amount payment screen

- frontend/src/screens/wallet/receive/ReceiveOnchain.tsx
- frontend/src/screens/wallet/swap/index.tsx
Fixes #1670
<table>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
> chore: replace divs with shadcn tab component

- go.mod
- go.sum
Fixes https://github.com/getAlby/hub/issues/1678
> fix: ldk relax maximum fee estimate confirmation target estimation

- README.md
- config/models.go
- lnclient/ldk/ldk.go
Closes https://github.com/getAlby/hub/issues/1642
Testing it with Mutinynet which is working well (LDK recommended testing it to compare how long syncs take since often mine is slow locally - also partially due to a poor internet connection.)
Also it's good to have more chain source options.
> feat: add ldk electrum chain source

- frontend/src/screens/setup/ImportMnemonic.tsx
> fix: alert styling in import mnemonic screen

- frontend/src/screens/channels/IncreaseOutgoingCapacity.tsx
> chore: add comfirmation modal before opening a channel

- frontend/src/screens/wallet/swap/SwapInStatus.tsx
- frontend/src/screens/wallet/swap/SwapOutStatus.tsx
> fix: see 1 confirmation and swap id

- frontend/src/screens/settings/DebugTools.tsx
> chore: add instructions to the refund swap dialog
